### ISSUE TITLE
multisite issue with PHPRedis serializer

### ISSUE THREAD

**Issue by kevinlisota** [rhubarbgroup/redis-cache#122]
I am attempting to switch our site to use the phpredis serializer. We are using phpredis 5.0.2.

Our site is multisite, with two site IDs.

I turn on the serializer with this in wp-config.php:
`define( 'WP_REDIS_SERIALIZER', 'Redis::SERIALIZER_PHP' );

This results in the site not loading with these errors:

```
PHP Warning:  Illegal string offset 'site_ids' in /wp-includes/class-wp-site-query.php on line 333
PHP Warning:  Illegal string offset 'found_sites' /wp-includes/class-wp-site-query.php on line 334
PHP Warning:  A non-numeric value encountered in /wp-includes/class-wp-site-query.php on line 339
PHP Warning:  array_map(): Expected parameter 2 to be an array, string given in //wp-includes/class-wp-site-query.php on line 348
PHP Warning:  Invalid argument supplied for foreach() in /wp-includes/functions.php on line 5933
PHP Warning:  Invalid argument supplied for foreach() in /wp-includes/class-wp-site-query.php on line 363
```

Not sure exactly what's happening here, though `site_ids` and `found_sites` are both cache values in WP. My guess is that they are not being desrialized before getting to class-wp-site-query.php.

Any thoughts?

Redis works fine with serializer turned off.

**Comment by lkraav** [comment]
I also had a very weird non-function result on a single site, whereas a couple of other installations have converted to `Redis::SERIALIZER_PHP` perfectly fine. :man_shrugging:

**Comment by tillkruss** [comment]
Can you post the values that are stored in Redis for those two keys?

**Comment by lkraav** [comment]
I had another weird experience right now, and based on how I managed to resolve it (flush, then change serializer) makes me think indeed some weird values get into Redis.

I'll know what to look for next time this happens and will post those values here.

**Comment by lkraav** [comment]
> I had another weird experience right now, and based on how I managed to resolve it (redis-cli FLUSHALL, then change serializer) makes me think indeed some weird values get into Redis.

It appears I now need to manually run `redis-cli FLUSHALL` whenever I updated `plugins/redis-cache` to overcome however it gets broken as described in issue opening comment.

Unfortunately I forgot to pull values during this incident, but I will try to keep it in mind for the next update.

**Comment by tillkruss** [comment]
@lkraav: Would you mind posting your diagnostics for that installation?

**Comment by lkraav** [comment]
```
Status: Connected
Client: PhpRedis (v5.2.1)
Drop-in: Valid
Ping: 1
Redis Extension: 5.2.1
Predis Client: 1.1.1
PHP Version: 7.4.6
Redis Version: 5.0.7
Multisite: Yes
Global Prefix: ""
Blog Prefix: 1
WP_REDIS_DISABLED: false
WP_REDIS_CLIENT: "pecl"
WP_CACHE_KEY_SALT: "cr_"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "blog_meta",
    "mo_cache"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Dropins: 
 - advanced-cache.php v by 
 - Query Monitor Database Class v by 
 - maintenance.php v by 
 - Redis Object Cache Drop-In v1.6.2 by Till Krüss
Plugins: 
<List of 600+ items>
```

**Comment by tillkruss** [comment]
So you're using the default serializer, but during a dropin update you site crashes?

**Comment by tillkruss** [comment]
Closing due to lack of feedback.
