### ISSUE TITLE
Race conditions in function add_or_replace

### ISSUE THREAD

**Issue by ffxluca** [rhubarbgroup/redis-cache#166]
My fellas are using the drop-in replacement in a quite big WordPress (single site) setup:
- 10 different apache webservers, each one running on a separate machine/vm.
- php-fpm (`pm` set to `dynamic`, up to 8 children each)

This is almost impossible to replicate but I have noticed the function `add_or_replace()` utilises `exists($derived_key);` and then `set()` or `setex()`, whereas it should instead utilise Redis' [setnx](https://redis.io/commands/setnx).

I am experimenting on a local branch (with php-redis version ~4 or ~5, and pecl client) so I'm going to open a pull request soon - that'll make it easier to understand what I'm trying to avoid

**Comment by tillkruss** [comment]
Are you encountering [this](https://core.trac.wordpress.org/ticket/31245)?

**Comment by ffxluca** [comment]
@tillkruss not really, we already have a workaround for that.

I cannot open new branches here so I cloned the repo, this is more or less the diff
https://github.com/ffxluca/redis-cache/commit/d1a528586e50b761152d98da08c227087c7c9eb3

**Comment by tillkruss** [comment]
Alright, can you submit a PR after you finished your testing?

**Comment by ffxluca** [comment]
Deffo 😃 I might need some help with testing the `predis` client and possibly the permission to push new branches here

**Comment by naxvog** [comment]
Just create a pull request from your own forked repository. You don't need any permission in this repo to do this.
Predis support is being dropped soon so I would not bother to test specifically for it (see https://github.com/tillkruss/redis-cache/issues/160).

**Comment by tillkruss** [comment]
Thanks @naxvog.

I won't drop Predis support until WP drops PHP 7.4, just switch over to a new default client when PhpRedis isn't installed.

**Comment by tillkruss** [comment]
@ffxluca: Were you able to test your fix?

**Comment by ffxluca** [comment]
@tillkruss yes, tested as in _nothing broke here_ I'll open a pull request and make more thorough tests :)
