### ISSUE TITLE
Detect renamed commands

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#171]
Commands fail silently when they've been renamed.

**Comment by naxvog** [comment]
A preflight test would be optimal running every day as well as every plugin update. Any issue would result in a notification as well as an admin email depending on the severity.
This test could be implemented as a WordPress site health test to use already existing APIs.

**Comment by tillkruss** [comment]
Site Health would be great, or we only check it when the settings page loads.

**Comment by naxvog** [comment]
Used commands:
* decrby
* del
* exists (will not be used once https://github.com/tillkruss/redis-cache/pull/170 gets merged) 
* flushdb
* get
* incrby
* info
* mget
* ping
* select
* set
* setex
* setnx

**Comment by naxvog** [comment]
So I tested a little and the implementation of phpredis is lacking severely in this regard.
We can only detect if a command returns an unexpected value as most of phpredis commands return `false` on such a case.
If we for example call `->info()` on a redis instance that has disabled this command `redis-cli` will return something like this ``ERR unknown command `INFO`, with args beginning with:`` while phpredis just returns `false`.

However we can write a suite of tests and check for expected results. Testing for renamed commands might be impossible.

**Comment by tillkruss** [comment]
Thanks for looking into it!

@michael-grunder: Could PhpRedis throw an exception in the next major version when a Redis command is called that has been renamed?

**Comment by tillkruss** [comment]
Talked with Michael, he's down with it.

https://github.com/phpredis/phpredis/issues/1769

**Comment by naxvog** [comment]
Just fyi: using `predis` with a renamed command will result in exceptions being thrown.
```
PHP message: Predis\Response\ServerException: ERR unknown command `INFO`, with args beginning with:  in /var/www/wp-content/plugins/redis-cache/includes/predis/src/Client.php:370
Stack trace:
#0 /var/www/wp-content/plugins/redis-cache/includes/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerInfoV26x), Object(Predis\Response\Error))
#1 /var/www/wp-content/plugins/redis-cache/includes/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerInfoV26x))
#2 /var/www/wp-content/object-cache.php(587): Predis\Client->__call('info', Array)
#3 /var/www/wp-content/object-cache.php(178): WP_Object_Cache->__construct(true)
```

**Comment by tillkruss** [comment]
Good to know. 

Let's see if [Credis](https://github.com/colinmollenhour/credis) does throw an exception too when we implement it.
