### ISSUE TITLE
Support `$force` in `wp_cache_get_multi()`

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#187]
WordPress 5.5 added support for `wp_cache_get_multi()`.

This plugin's implementation was overhauled in 4fe9060, but currently doesn't respect the `$force` parameter.

- [x] When `$force` is set: `MGET` all requested `$keys`
- [x] When `$force` is not set: only `MGET` keys that aren't already cached internally
- [x] Switch to the faster `get_from_internal_cache()` for ignored groups (and also increment `$stats`)

**Comment by tillkruss** [comment]
@naxvog: Do you want to give this a shot?

**Comment by naxvog** [comment]
@tillkruss Currently quite busy. Can go for it in about a week

**Comment by tillkruss** [comment]
6089240fdd721adb653cc29d6e20ec15ae9c0846
