### ISSUE TITLE
update drop-in on plugin update

### ISSUE THREAD

**Issue by StuPagely** [rhubarbgroup/redis-cache#191]
When the plugin is updated with `wp plugin update redis-cache`, it does not also update the drop-in. So that `wp-content/object-cache.php` would end up as an earlier version than the installed plugin.

**Comment by tillkruss** [comment]
Yeah, the Pro version is doing that. Will push this into v2.

For now you could always run:

```
wp plugin update redis-cache
wp redis update-dropin
```
