### ISSUE TITLE
Metrics improvments

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#205]
- [x] Improve `WP_REDIS_DISABLE_METRICS` documentation
- [x] Hide Pro line when banners are disabled
- [x] Indicate that Metrics are disabled by showing grayed-out tab
- [x] Provide context to metrics via "Info" popover (like Jetpack stats) really explain what each metric means
- [ ] Remember chart selection via cookie

**Comment by naxvog** [comment]
Just a note as I came back to work and updated the plugin on my client's websites:
`WP_REDIS_DISABLE_METRICS` was used before 2.x as a flag determining if metrics were sent to an external resource. Now it is reused to determine if (internal) metrics should be collected.
I would assume that some people still have this flag set - we should at least clarify the flag on the wiki page.
