### ISSUE TITLE
2.0 Release Testing

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#206]
[Release Candidate 1](https://github.com/rhubarbgroup/redis-cache/releases) of v2.0 is out. It should be stable and a seamless upgrade.

Please test it in your staging environments, so we don't take down production sites on release day.

**Comment by tillkruss** [comment]
@naxvog: Thoughts on getting #161, #173, #202 and #205 done before release?

**Comment by naxvog** [comment]
> 
> 
> @naxvog: Thoughts on getting #161, #173, #202 and #205 done before release?

- #161 considerable amount of refactoring and rewriting necessary - not for 2.0
- #173 even after implementation this feature needs a lot of testing - don't know if I can implement this before 2.0 but this might be a nice addition in a feature release
- #202 Supports only one Sentinel instance. Will implement it like Credis throwing in case multiple sentinels were configured - will be in 2.0: next on my todo list
- #205 is a nice to have, not necessary for 2.0 imho
