### ISSUE TITLE
Avoid SELECT command unless WP_REDIS_DATABASE set

### ISSUE THREAD

**Issue by eigrobert** [rhubarbgroup/redis-cache#208]
The plugin is issuing a "select 0" to the redis server even if WP_REDIS_DATABASE is not defined.  We should avoid the extra command unless WP_REDIS_DATABASE is set.

This causes fatal errors with redis6 if the user connecting doesn't have access to the select command.

**Comment by tillkruss** [comment]
Resolved in 64a60ad7bfd8c130bb1b59ad47154552bee666a9.
