### ISSUE TITLE
Using Credis instead of Predis

### ISSUE THREAD

**Issue by dmhendricks** [rhubarbgroup/redis-cache#227]
I recently upgraded from 1.6.3 to 2.0.3 and I'm getting the following warning on the settings page:
> _The Predis library is not reliable on PHP 7.2 and newer. Consider switching over to Credis or PhpRedis to avoid compatiblity issues._

On production environments, I use the latest [PhpRedis](https://github.com/phpredis/phpredis), however, for local development, I have been using [Local](https://localwp.com/) (which, despite many appeals to the developers, does not have the PhpRedis extension in the stack).

Question: What is the recommended way to use/load [Credis](https://github.com/colinmollenhour/credis)? I assume that I need to load the class somewhere, but I'm wondering how/when/where since I imagine that it needs to be done before the drop-in is loaded. Thank you.

- **WordPress:** 5.4.2
- **PHP:** 7.4.1
- **nginx:** 1.16.0
- **OS:** macOS 10.15.2

<img width="618" alt="Redis Object Cache 2.0.3 Settings Page" src="https://user-images.githubusercontent.com/8184361/87539919-60209a00-c664-11ea-8d97-08ffaa5596f8.png">

**Comment by naxvog** [comment]
You have to specify `define( 'WP_REDIS_CLIENT', 'credis' );` in your `wp-config.php` to use Credis. Everything other is done automatically as Credis is bundled in version 2.x

**Comment by dmhendricks** [comment]
Perfect, thank you! May wish to add to [Configuration Options](https://github.com/rhubarbgroup/redis-cache/wiki/Configuration-Options) wiki page.

**Comment by naxvog** [comment]
Informed till about the missing documentation

**Comment by tillkruss** [comment]
It's added.
