### ISSUE TITLE
Integrate filesystem issues into "Overview" tab

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#232]
Test 4ec9bf973d6bbd6d77e093b6a97ac0a035f97781 for little bit, make sure it actually works well and then integrate it into the _Overview_ tab, highlight it in red when there is an error.

**Comment by thefrosty** [comment]
Assuming this is related to `copy(/...wp-content/.redis-write-test.tmp): failed to open stream: Permission denied`

<img width="1665" alt="Screen Shot 2020-10-14 at 8 05 20 AM" src="https://user-images.githubusercontent.com/367897/96008158-1e82c500-0df4-11eb-8267-40ffdad7383e.png">

If not I will open a new issue. 

_This is a docker install with limited permissions._ 

WP: `5.5.1`
Redis Plugin: `2.0.15`
