### ISSUE TITLE
Switching tabs unexpected anchor scrolling

### ISSUE THREAD

**Issue by naxvog** [rhubarbgroup/redis-cache#234]
With the removal of the `#top` anchor before the tab target (e.g. `#top#metrics`) switching a tab automatically scrolls to the tab content. This results in the tab bar itself not showing and is quite frankly an awkward user experience.

The `#top` anchor was removed because forced scrolling should be avoided to improved the UX but the current behaviour is worse in my opinion.
Clicking a tab should always result in displaying the top part of the page including the tab bar.

The original approach was modelled after Yoast SEO. Given its number of installations, the plugin's scope and its rapid development cycle I would assume that they did some UX testing and concluded that this behaviour is superior to others.

**Comment by tillkruss** [comment]
Can you post a screen recording of the issue?

**Comment by naxvog** [comment]
![screencast-20200723-09-07-34-Tri](https://user-images.githubusercontent.com/4963183/88260588-f851fb00-ccc4-11ea-9196-bc1623f3512f.gif)

**Comment by tillkruss** [comment]
Wow, is that IE?

**Comment by naxvog** [comment]
FF 79.0b9

**Comment by naxvog** [comment]
But this should be the default behaviour in all browsers as the anchor of the content element is selected. Returning `false` in the jQuery method should result in a fix as the click event won't propagate further.

**Comment by tillkruss** [comment]
@naxvog: Feel free to improve 88e9577 if necessary.

**Comment by naxvog** [comment]
in 2.0.7 tabs are unusable:
Tab nav links don't have an anchor linking to `wp-admin/metrics` for example. Tabs are not hidden by default. Its a mess currently.

Please consider implementing my tested PR #235 

![DOM-Node screenshot](https://user-images.githubusercontent.com/4963183/88772466-1dd97b80-d181-11ea-8ff9-36d3cced3e7f.png)

**Comment by tillkruss** [comment]
The `#top` solution is backwards. The `admin.js` file wasn't properly copied to wp.org's SVN repo.
