### ISSUE TITLE
Credis master - slave load distribuition

### ISSUE THREAD

**Issue by pinheiroalexandre2** [rhubarbgroup/redis-cache#238]
Hey! 

I have a simple master-slave redis setup and I use Predis as client.

When I upgraded to Credis I noticed that the biggest part of the requests are being sent to slave and just some requests to master. 

This is a screenshot where you can see this behavior:
![Screenshot from 2020-07-24 12-21-01](https://user-images.githubusercontent.com/3235813/88386433-47bd2780-cda8-11ea-9156-7e794def645f.png)

This is my wp-config.php configuration:
```
# Redis
define( 'WP_REDIS_SERVERS', [
        'tcp://0.0.0.29:6379?alias=master',
        'tcp://0.0.0.45:6379?alias=slave-01',
] );
```
 
I choose Credis instead of PhpRedis, because I can't figured how to connect to PhpRedis with a master-slave setup.

Regards!

**Comment by tillkruss** [comment]
That would be more of a question to pose in https://github.com/colinmollenhour/credis

**Comment by naxvog** [comment]
Credis states that in order to avoid a non balanced situation you should specify the same server multiple times in small setups.

Internally the key is hashed and the hash directs a key to its server so that the same key will be served from the same server every time.

```To avoid an uneven distribution of keys (especially on small clusters), it is common to duplicate target nodes. Based on the number of replicas, each target node will exist n times on the "ring". ```

We could force balance if we multiply each defined server by a factor to have... let's say 20.
This should avoid such unbalanced situations

**Comment by tillkruss** [comment]
Nah, let's just add it as a note 👍🏻

**Comment by naxvog** [comment]
I misread that this is a master/slave issue.
Credis will also perform read/write separation only writing to the master and reading from all by default.

You can change that using the `write_only` flag in your connection string:
```php
# Redis
define( 'WP_REDIS_SERVERS', [
        'tcp://0.0.0.29:6379?alias=master&write_only=false',
        'tcp://0.0.0.45:6379?alias=slave-01',
] );
```
This should give you a more balanced load regarding Redis reads.

Edited my comment above to reflect this.

Reference: https://github.com/colinmollenhour/credis#masterslave-replication

**Comment by naxvog** [comment]
I propose the following 2 notices when using Credis:

**Master/Slave setup without write_only flag(s) set**
```You are using Credis in a master/slave configuration. Please be aware that Credis will perform read/write separation only writing to the master and only reading from the slave(s). [link]More information[/link]```
**Multiple but less than 5 redis instances**
```You are using Credis in a multi instance configuration. Please be aware that it is advised to duplicate your instances in your configuration to better balance the load. [link]More information[/link]```

The links should point to our wiki and reference the Credis documentation.
