### ISSUE TITLE
Flush button not showing up

### ISSUE THREAD

**Issue by xberg** [rhubarbgroup/redis-cache#240]
Hi,
I upgraded today from 1.x to 2.0.7 and I am having the following problems:
- no more flush / disable button as in version 1.x
- the Metrics and Diagnostics tabs do nothing when clicked

This is what I see in overview:

Status: Connected
Client: PhpRedis (v5.3.0)
Drop-in: Valid
Disabled: No
Filesystem: Working
Ping: 1
Errors: []
PhpRedis: 5.3.0
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.3.20
Plugin Version: 2.0.7
Redis Version: 2.8.17

**Comment by tillkruss** [comment]
Relevant: https://wordpress.org/support/topic/no-flush-button-metrics-and-diagnostics-go-nowhere/#post-13186587

**Comment by tillkruss** [comment]
@xberg Are you seeing any errors in your PHP log files?

Is it a multisite installation?

**Comment by tillkruss** [comment]
Try updating to 2.0.8 and:

- Delete the `object-cache.php` dropin by hand (FTP)
- Flush you Redis database (`redis-cli flushall`)
- Re-enable the plugin via `Settings -> Redis`
- Try flushing again

**Comment by naxvog** [comment]
The Flush button currently only shows up if a redis connection is established successfully.

Related: #241

**Comment by tillkruss** [comment]
I'll also test this with a foreign dropin and when the dropin can't be read, maybe an invalid header or something.

**Comment by tillkruss** [comment]
@xberg: Can we debug this via Zoom? This seems like an obscure bug.

**Comment by xberg** [comment]
Hi,
I upgraded to 2.0.10 and everything works perfectly now. Well done!
sorry for my late reply!
