### ISSUE TITLE
Can't login to `wp-admin` after upgrading to WP 5.5

### ISSUE THREAD

**Issue by joshuaja** [rhubarbgroup/redis-cache#244]
If I remove/rename `object-cache.php` everything works again.

Is there anything I can try or how can I help to troubleshoot?

**Comment by tillkruss** [comment]
Did you see any errors in your logs?

**Comment by Onatcer** [comment]
We've experienced this problem with the upgrade too. We tried upgrading the wordpress and the plugin both to the latest version. There were no errors reported by sentry but the cache obviosly wasn't working as expected at all. It looked like wordpress didn't recieve any data at all from the redis cache.

**Comment by tillkruss** [comment]
@Onatcer: Did you try a `FLUSHALL`?

**Comment by Onatcer** [comment]
@tillkruss Yes, `FLUSHALL` did not have any visible effect. Both wordpress and redis are running in an docker environment if that makes any difference.

**Comment by tillkruss** [comment]
Are you up for a Zoom?

**Comment by tillkruss** [comment]
@Onatcer: From someone who had issues:

> Our recommendation to update Redis -> 2.0.10 from 2.0.8 if you didn't WordPress to 5.5:
> 1. Disable Object Cache (Tools-> Redis)
> 2. Update to 5.5
> 3. whatever cache plugin you are using - use:
> clear cache
> Pre-load
> regenerate CSS
> 4. Update Redis plugin
> 5. FLASHALL
> 
> We also added one more step, clear again the caching plugin, and pre-load it back to our procedure - but it should work even without it.
> 
> If you already update both and having problems:
> 1. Disable both f the plugin
> 2. manual log to Redis-cli: FLASHALL
> 3. enable the cache plugin you are using - use:
> clear cache
> Pre-load
> regenerate CSS
> Re-enable Redis plugin after.

**Comment by Onatcer** [comment]
@tillkruss 

Thanks for the quick reply. I was just able to reproduce it on a fresh docker compose environment with a wordpress and redis service similar to our production setup, so I don't think it's an issue with the upgrading process. Also we do not use any other caching plugins. 

You can find the docker-compose here: https://gist.github.com/Onatcer/5cf18bc4c3526136d752298ba4ee60f7

Steps to reproduce: 

1. `docker-compose up -d`
2. (Give it a few seconds to start up) Go to http://localhost:8585/ and quickly provide some test credentials to setup the test environment
3. Log in
4. Install and activate Redis Object Cache from the Plugin Directory
5. Navigate to the Plugin Settings and hit enable Object Cache

After that you'll be logged out and won't be able to login again. 

The only "non-standard" config that is supplied with this docker compose file is the       
```
WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
```
environment variable. It just points to the redis container in the docker compose connected through a network.

I hope this helps, I'm open for a zoom too, not sure i can provide you with any more useful information than that tho. You can reach me via me@onatcer.com

**Comment by tillkruss** [comment]
@naxvog: I can't reproduce this, kannst du?

**Comment by tillkruss** [comment]
Looks like `wp-login.php` is returning a 302:

```
Request URL: http://localhost:8585/wp-login.php
Request Method: POST
Status Code: 302 Found
```

**Comment by tillkruss** [comment]
Weird things going on with the `user_meta` group.

```
1597429047.662431 [0 172.18.0.3:46060] "SELECT" "0"
1597429047.662761 [0 172.18.0.3:46060] "PING"
1597429047.663224 [0 172.18.0.3:46060] "INFO"
1597429047.664885 [0 172.18.0.3:46060] "GET" "wp:default:is_blog_installed"
1597429047.667593 [0 172.18.0.3:46060] "GET" "wp:options:notoptions"
1597429047.667839 [0 172.18.0.3:46060] "GET" "wp:options:alloptions"
1597429047.668452 [0 172.18.0.3:46060] "GET" "wp:site-options:1-notoptions"
1597429047.671560 [0 172.18.0.3:46060] "GET" "wp:userlogins:admin"
1597429047.671749 [0 172.18.0.3:46060] "GET" "wp:users:1"
1597429047.672168 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.672483 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.672771 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.672933 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.676397 [0 172.18.0.3:46060] "GET" "wp:options:can_compress_scripts"
1597429047.677343 [0 172.18.0.3:46060] "GET" "wp:transient:doing_cron"
1597429047.677653 [0 172.18.0.3:46060] "SET" "wp:transient:doing_cron" "1597429047.6772389411926269531250"
1597429047.681703 [0 172.18.0.3:46060] "MGET" "wp:posts:1"
1597429047.682048 [0 172.18.0.3:46060] "GET" "wp:category_relationships:1"
1597429047.682246 [0 172.18.0.3:46060] "MGET" "wp:terms:1"
1597429047.682524 [0 172.18.0.3:46060] "GET" "wp:post_tag_relationships:1"
1597429047.682789 [0 172.18.0.3:46060] "GET" "wp:post_format_relationships:1"
1597429047.686065 [0 172.18.0.3:46060] "GET" "wp:posts:last_changed"
1597429047.686267 [0 172.18.0.3:46060] "GET" "wp:posts:get_pages-2f54e37d83f6d62e02f196e9e7b977b5-0.71810500 1597428677"
1597429047.686513 [0 172.18.0.3:46060] "GET" "wp:posts:2"
1597429047.687516 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.687642 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.688017 [0 172.18.0.3:46060] "GET" "wp:post_meta:1"
1597429047.688144 [0 172.18.0.3:46060] "MGET" "wp:post_meta:1"
1597429047.688900 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.689051 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.689996 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.690283 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.690695 [0 172.18.0.3:46060] "GET" "wp:post_meta:1"
1597429047.690836 [0 172.18.0.3:46060] "MGET" "wp:post_meta:1"
1597429047.691580 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.691715 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.692078 [0 172.18.0.3:46060] "GET" "wp:user_meta:1"
1597429047.692222 [0 172.18.0.3:46060] "MGET" "wp:user_meta:1"
1597429047.693429 [0 172.18.0.3:46060] "GET" "wp:comment:last_changed"
1597429047.693536 [0 172.18.0.3:46060] "GET" "wp:comment:get_comments-a83484ce4441a2d87a90609f886c4a28-0.72739200 1597428677"
1597429047.693782 [0 172.18.0.3:46060] "MGET" "wp:comment:1"
1597429047.694286 [0 172.18.0.3:46060] "GET" "wp:posts:wp_get_archives-53058f6b83972cfc3253e30ef06fcaa9-0.71810500 1597428677"
1597429047.694794 [0 172.18.0.3:46060] "GET" "wp:terms:last_changed"
1597429047.694897 [0 172.18.0.3:46060] "GET" "wp:terms:get_terms-55e00a2479938f82355c3418aae351a9-0.72006400 1597428677"
1597429047.696315 [0 172.18.0.3:46060] "ZADD" "wp:redis-cache:metrics" "1597429047" "i=37a9f8c;h=863;m=24;r=97.3;b=16446;t=0.00792;c=41"
```

**Comment by tillkruss** [comment]
Group doesn't exist:

```
127.0.0.1:6379> KEYS wp:user*
1) "wp:useremail:till@kruss.io"
2) "wp:userslugs:admin"
3) "wp:userlogins:admin"
4) "wp:users:1"
```

**Comment by tillkruss** [comment]
A quick workaround for now is:

```php
define('WP_REDIS_IGNORED_GROUPS', ['counts', 'plugins', 'user_meta']);
```

**Comment by naxvog** [comment]
We could introduce a version hash of the current plugin version and the WordPress version to avoid retrieving stale data.
The key format would be `{$salt}:{$version_hash}:{$prefix}:{$group}:{$key}`. The problem might be that there are some old keys in the database that should be cleaned eventually.

**Comment by tillkruss** [comment]
@naxvog: We could do that. Maybe a background task to delete all old keys to free up space.

The issue also happens with a clean database.

**Comment by tillkruss** [comment]
This was resolve in 0eb1a2e and 051f2ae.

@joshuaja and @onatcer can you try the 2.0.11 release from GitHub?

**Comment by Onatcer** [comment]
Just installed it on one of our staging instances. Looking good 👍 
Dankeschön
