### ISSUE TITLE
Redis modules - how to use from WordPress / PHP

### ISSUE THREAD

**Issue by rvencu** [rhubarbgroup/redis-cache#245]
I found that Redis server can be enhanced with new data structures and I realized I could replace my PHP trie implementation with a much faster, supposedly, Redis trie implementation via an existing Redis module.

I was able to install Redis 5.0.0 and compile/load the trie module. Now I suppose I need a way to use the new commands that are exposed by trie module from my plugin and I am curious if such thing already exists versus some customization is required versus is impossible/not implemented at all in PHP.

Thanks.

**Comment by tillkruss** [comment]
You can always call raw commands with Predis or PhpRedis:

https://github.com/phpredis/phpredis#rawcommand
