### ISSUE TITLE
No WP_REDIS_SERVERS Support With PhpRedis Client

### ISSUE THREAD

**Issue by davidbitton** [rhubarbgroup/redis-cache#248]
I setup my system with PhpRedis. I can see from the plugin's code, there isn't a provision for this define in the connect w/ PhpRedis method. I thought I read that Predis was on it's way out and I shouldn't use it. I have a single Redis ElastiCache instance. There is a single shard, and I have thee nodes; one primary and 2 replicas. What is the proper was to setup Redis Object Cache for a Redis ElastiCache instance that is not a cluster? Thanks!

**Comment by tillkruss** [comment]
Predis was recently resurrected: https://github.com/predis/predis/issues/587#issuecomment-671791015

You can keep using it.

**Comment by davidbitton** [comment]
Shazam! I just changed it to 'predis' and it's working again. Thanks.
