### ISSUE TITLE
Growth in not-expiring keys (metrics?)

### ISSUE THREAD

**Issue by jacklenox** [rhubarbgroup/redis-cache#254]
Hello,

I've been using this plugin for a couple of months and I've noticed that for all the time it's activated, the number of not-expiring keys just constantly grows at a steady rate of about 1,500 per week, regardless of other environmental factors.

I monitor Redis using Grafana so you can see this illustrated in the following graphs:

![Screenshot_2020-08-20 Redis Dashboard for Prometheus Redis Exporter 1 x - Grafana](https://user-images.githubusercontent.com/751476/90752271-7959dd80-e2d7-11ea-99f9-0675495d6fbc.png)

![Screenshot_2020-08-20 Redis Dashboard for Prometheus Redis Exporter 1 x - Grafana(1)](https://user-images.githubusercontent.com/751476/90752351-8d9dda80-e2d7-11ea-9421-a8831444078f.png)

I should add this is on a dormant WordPress installation, so no significant new data is being added to the database.

I've tried purging the cache but sure enough it just starts again every time. And this is definitely isolated to this plugin as when I disable the plugin, the growth in not-expiring keys stops.

In the meantime I've switched to using the WP Redis plugin and this seems to have stopped happening.

Thanks,
Jack

**Comment by naxvog** [comment]
Hi Jack,
could you please post your diagnostics data? There are so many supported configurations it is impossible to figure out what the issue might be.
Also is it just the transients or does this happen to all keys?

**Comment by tillkruss** [comment]
I can't reproduce this on large installs, we'd need to see what keys are not expiring.

You can find that out with this command:

```bash
redis-cli --scan | while read LINE ; do TTL=`redis-cli ttl "$LINE"`; if [ $TTL -eq  -1 ]; then echo "$LINE"; fi; done;
```

It's likely the `*redis-cache:metrics` hash map and it's containing keys. In your particular case the `rediscache_discard_metrics` event isn't called every hour to purge old metrics.

You can disable the metrics to see if the issue disappears:

```
define( 'WP_REDIS_DISABLE_METRICS', true );
```

**Comment by markhughes** [comment]
There are a lot of plugins - and even WordPress internals - that don't set transient expiries by design.

**However** some plugins use transients simply because its easy (which is a bad design choice, they should use the options API). Setting the Max TTL is your safest bet here, and if you need some transients to bypass this, you can use the filter [redis_cache_expiration](https://github.com/rhubarbgroup/redis-cache/wiki/Hook-reference#redis_cache_expiration) and fall back to the original expiry.

**Comment by jacklenox** [comment]
I can confirm that setting the Max TTL has resolved this issue. It seems there are no keys that ignore this. I wonder if the Max TTL should be set to some sort of sane default though? Or at least, more weight should be given in the documentation that you _definitely should_ set this.

It also still isn't clear to me why infinite new keys are added if a Max TTL hasn't been set. Surely a point should be reached when all of the keys that can be set, have been set. But I'm a Redis beginner so perhaps I'm misunderstanding something here.

Anyway, thanks for the help!

**Comment by naxvog** [comment]
Setting a default TTL might be an enticing option but there might be plugins around relying on the expiry of a transient in a specified timeframe. Not saying that I've seen such plugins but yeah this would be one of the afore mentioned misuse of the transient system.

Also your Redis instance has an eviction policy configured that purges keys if necessary (if you have `noeviction` eviction policy configured I strongly advise you to re-evaluate this decision :wink: ) so too many keys should not really be problematic.

Please contact the specific plugin developer about this issue as this can easily be avoided.

**Comment by tillkruss** [comment]
The WP object cache and transients API both default to `0` (no expiration). MaxTTL should be set on an individual basis IMO. 

Redis also holds 2^32 keys, so adding 1500 a week isn't a real issue.
