### ISSUE TITLE
Pass original expiry to redis_cache_expiration

### ISSUE THREAD

**Issue by markhughes** [rhubarbgroup/redis-cache#257]
I have a case where I want some key types to override the original `WP_REDIS_MAXTTL` being used..

The filter `redis_cache_expiration` does not pass the original expiry, I'm currently hacking it in manually by changing:

```php
$expiration = apply_filters( 'redis_cache_expiration', $this->validate_expiration( $expiration ), $key, $group );
```

to:

```php
$expiration = apply_filters( 'redis_cache_expiration', $this->validate_expiration( $expiration ), $key, $group, $expiration );
```

However, you might know an alternative to this, I had a few ideas such as a adding a `should_validate_expiration` for key/group filter. What are your thoughts? 

If you think my current solution is good, or a `should_validate_expiration` filter I can go ahead and create a PR for you. :)

**Comment by tillkruss** [comment]
You mean the 1st argument is always overwritten by `WP_REDIS_MAXTTL`? If so, then yeah, let's pass a 4th argument to that filter 👍🏻

```php
$expiration = apply_filters(
    'redis_cache_expiration',
    $this->validate_expiration( $expiration ), // <-- is overwritten by `WP_REDIS_MAXTTL`
    $key,
    $group
);
```

**Comment by markhughes** [comment]
Cheers, redis-cache is the only redis cache plugin that really adds in the extra "ooft" that developers need 😄

**Comment by tillkruss** [comment]
Thanks Mark! If you want to leave a review on WP.org, that would be magnificent 😗
