### ISSUE TITLE
Issue with multisite and PHPredis igbinary serializer

### ISSUE THREAD

**Issue by orenwolf** [rhubarbgroup/redis-cache#269]
Hello!

We're running WP 5.5.1 on PHP 7.4.

php -i shows:

 ```
$ php -i | egrep -i '(redis | igbinary)'
memcached.serializer => igbinary => igbinary
Redis Support => enabled
Redis Version => 5.3.1
Redis Sentinel Version => 0.1
Available serializers => php, json, igbinary, msgpack
Registered save handlers => files user memcached redis rediscluster 
Registered serializer handlers => php_serialize php php_binary igbinary msgpack 
```

Site is a subdomain multisite.

If I enable `define('WP_REDIS_SERIALIZER', 'Redis::SERIALIZER_IGBINARY');`, the site will fail with the following:

```
PHP Warning:  Illegal string offset 'site_ids' in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 340
Warning: Illegal string offset 'site_ids' in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 340
PHP Warning:  Illegal string offset 'found_sites' in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 341
Warning: Illegal string offset 'found_sites' in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 341
PHP Warning:  A non-numeric value encountered in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 345
Warning: A non-numeric value encountered in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 345
PHP Warning:  array_map(): Expected parameter 2 to be an array, string given in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 354
Warning: array_map(): Expected parameter 2 to be an array, string given in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 354
PHP Warning:  Invalid argument supplied for foreach() in /var/www/wordpress/wp-includes/functions.php on line 6384
Warning: Invalid argument supplied for foreach() in /var/www/wordpress/wp-includes/functions.php on line 6384
PHP Warning:  Invalid argument supplied for foreach() in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 369
Warning: Invalid argument supplied for foreach() in /var/www/wordpress/wp-includes/class-wp-site-query.php on line 369
```

wp cli further believes that `DOMAIN_CURRENT_SITE` is not set suggesting those defines are being munged somehow.

I commanded a redis `FLUSHALL` before and after enabling.

Debug output when the plugin is running (but with the default serializer):

```
Status: Connected
Client: PhpRedis (v5.3.1)
Drop-in: Valid
Disabled: No
Filesystem: Working
Ping: 1
Errors: []
PhpRedis: 5.3.1
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.9
Plugin Version: 2.0.13
Redis Version: 5.0.6
Multisite: Yes
Global Prefix: ""
Blog Prefix: 1
WP_REDIS_HOST: "redis.x.ng.0001.az.cache.amazonaws.com"
WP_REDIS_MAXTTL: 300
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Drop-ins: [
    "Redis Object Cache Drop-In v2.0.13 by Till Krüss"
]
```

I noticed this issue was mentioned in #122 but the reporter disappeared. I'd like to continue down that path if you're willing, and I'm happy to provide whatever environmental, diagnostic or testing assistance I can to find a resolution.

Thank you for your time. I appreciate you working on this plugin and your efforts to provide a modern object cache option for Wordpress!

**Comment by tillkruss** [comment]
You're treating the class constant as a string, try removing the apostrophes and flush you cache.

**Comment by orenwolf** [comment]
Yes, that solved it. 

May I suggest updating the wiki to show the format folks should be adding explicitly to their `wp-config.php`? I wonder also if, for example, people add values like `WPREDIS_MAXTTL` as strings as well.

Thanks again for the quick response and fast turnaround! Now I just need to figure out why the site falls over when the redis instance fills up and it starts evicting!

**Comment by tillkruss** [comment]
Did you set an eviction policy on your Redis instance?

**Comment by orenwolf** [comment]
I did, I set `allkeys-lru` as well as enabling the various `lazyfree` options. The issues are definitely in redis, not the plugin (as even connections to `redis-cli` are affected.

Thanks again, and sorry for the unnecessary issue report!

**Comment by tillkruss** [comment]
That's alright. Using serialization is smart, you might want to consider the LZ4 compression in the Pro version to further reduce the dataset size. 

Or alternatively, can you just bump you instance size to avoid Redis having to evict?
