### ISSUE TITLE
Add optional admin bar node to flush cache

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#272]
```php
add_action('admin_bar_menu', [$this, 'add_admin_bar_menu'], 1000);

public function add_admin_bar_menu($wp_admin_bar)
{
    if (! current_user_can(is_multisite() ? 'manage_network_options' : 'manage_options')) {
        return;
    }

    if (! $this->get_redis_status()) {
        return;
    }

    if (! defined('WP_REDIS_DISABLE_ADMINBAR') || WP_REDIS_DISABLE_ADMINBAR) {
        return;
    }

    $wp_admin_bar->add_node([
        'id' => 'redis-cache-flush',
        'title' => __('Flush Object Cache', 'redis-cache'),
        'href' => $this->action_link('flush-cache'),
        'meta' => [
            'title' => __('Flush the Redis object cache', 'redis-cache'),
        ],
    ]);
}
``

**Comment by naxvog** [comment]
I like the simplicity of that solution but think such a link should not redirect the user to a different admin page but should just execute the action and show a message on the current admin page.

We could add a second parameter to the `action link` method to achieve this. Might need some extra work to allow the plugin actions to run on non plugin pages.

Additionally we should deactivate the entry if a caching plugin already allows for an object cache flush in their own admin bar menu (e.g. WP Rocket) and optionally figure out how to integrate our flush method to their menu if possible.

**Comment by tillkruss** [comment]
Agreed, flush on the current page without redirecting to settings.

Integration with existing adminbar nodes would be neat. I was thinking of making this node opt-in, and maybe we can just make it configureable, if users want to inject it to specific nodes.

**Comment by B0nifaci0** [comment]
I have a problem on my site. my slider is cached I do not want my slider to be cached or a section of my site these sections are from my thema I use jannah for my blog and they use ajax for this section the question is just by putting the id that is in it div from that section is enough or I have to perform a function like this.

**Comment by tillkruss** [comment]
@B0nifaci0: Wrong place to ask for support.

**Comment by tillkruss** [comment]
Closing in favour of #224.
