### ISSUE TITLE
Dashboard widget appears in site language instead of user language

### ISSUE THREAD

**Issue by johnbillion** [rhubarbgroup/redis-cache#278]
Given a site with multiple languages installed, the "Redis Object Cache" dashboard widget always shows in the language of the site, not the chosen language of the user.

To reproduce:

* Install a non-English language that is supported by Redis Cache, for example Russian
* Change the site language to this language and ensure your translations are up to date
* Change your user language back to English from your user profile screen
* View the dashboard and observe that the widget is in Russian (the site language) instead of English (the user language)

**Comment by johnbillion** [comment]
<img width="499" alt="" src="https://user-images.githubusercontent.com/208434/93761693-1de87b80-fc06-11ea-9e04-af84fea93e58.png">

**Comment by tillkruss** [comment]
Any leads to why it's not translating?

https://github.com/rhubarbgroup/redis-cache/blob/develop/includes/ui/widget.php

**Comment by johnbillion** [comment]
Oh this affects the whole plugin. Its settings screen, its description on the Plugins screen, etc.

**Comment by johnbillion** [comment]
Ah-ha. This is caused because `\Rhubarb\RedisCache\Plugin::__construct()` calls `load_plugin_textdomain()` immediately instead of on the `init` hook.
