### ISSUE TITLE
Filter needed for validate_object_cache_dropin

### ISSUE THREAD

**Issue by rvencu** [rhubarbgroup/redis-cache#283]
I need to control my object caching behaviour based on some conditions, therefore I need to write my own object-cache.php file and load redis-cache object-cache.php file from plugin folder based on some conditions.

The mentioned function just stands in the way of my approach and I would appreciate if you can include a filter before return statement of Rhubarb\RedisCache\Plugin::validate_object_cache_dropin so I could automate my code.

**Comment by tillkruss** [comment]
Sure thing. Submit a PR 👍🏻

**Comment by rvencu** [comment]
Thanks, https://github.com/rhubarbgroup/redis-cache/pull/284
