### ISSUE TITLE
WooCommerce - upon new order received, whole redis cache gets flushed.

### ISSUE THREAD

**Issue by rwkyyy** [rhubarbgroup/redis-cache#289]
Hi there, I've added redis to a website that has a lot of orders, in the hope that redis will cache the postmeta table well.

This is needed as we are doing extra checks for each listed order in the admin screen to find any duplicate order with ongoing statuses.

The issue is that if you list the latest 20 orders, it loads slow, then if you reload the page it's almost instant (redis serving the previous queries), but if a new order is received, it's data is not added to the cache, but erased completely.

I've checked the wiki and didn't find anything on altering this behaviour.

**Comment by lkraav** [comment]
Have you located any WC codebase fragment you think might be responsible for pot. inappropriate cache flush you're seeing?

**Comment by rwkyyy** [comment]
@tillkruss none, but maybe these help:
https://ibb.co/p1Bjst4 - initial load
https://ibb.co/BL5x5NR - initial load - page refresh
https://ibb.co/rbWRbdD - order status change OR new order arrived

basically, any changes that is done to an order, flushes the cache

**Comment by naxvog** [comment]
Hey @rwkyyy ! You can use the following hook to determine what is causing the flush event:
```php
/**
 * Fires on every cache flush
 *
 * @since 1.3.5
 * @param null|array $results      Array of flush results.
 * @param int        $delay        Given number of seconds to waited before invalidating the items.
 * @param bool       $seletive     Whether a selective flush took place.
 * @param string     $salt         The defined key prefix.
 * @param float      $execute_time Execution time for the request in seconds.
 */
do_action( 'redis_object_cache_flush', $results, $delay, $selective, $salt, $execute_time );
```

You might add a function like this to find the cause:
```php
add_action( 'redis_object_cache_flush', function() {
  ob_start();
  var_dump( debug_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS );
  error_log( ob_get_clean(), 3, ABSPATH . 'cache-flush.log' );
} );
```

**Comment by tillkruss** [comment]
@rwkyyy did you find out what the issue is?

**Comment by rwkyyy** [comment]
@tillkruss not yet, been busy with others, will come back and post results as soon as I make time for debugging this issue

**Comment by rwkyyy** [comment]
Hi there,

I've added the action but no logs get created (search entire directory via ssh -> find . -name cache-flush.log); tried after manual flush and after automatic flush when new order is added in the database.

This is the system diagnostics (hope it helps):
Status: Connected
Client: PhpRedis (v5.3.1)
Drop-in: Valid
Disabled: No
Filesystem: Working
Ping: 1
Errors: []
PhpRedis: 5.3.1
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.1
Plugin Version: 2.0.15
Redis Version: 6.0.6
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_PREFIX: "A[u9jk2Oa,Pa;w8a`[b~h]#o[rjNXYkSeWio/QB?t](yTcZZg^=erF][b|0?@NUu"
WP_CACHE_KEY_SALT: "A[u9jk2Oa,Pa;w8a`[b~h]#o[rjNXYkSeWio/QB?t](yTcZZg^=erF][b|0?@NUu"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Drop-ins: [
    "advanced-cache.php v by ",
    "Redis Object Cache Drop-In v2.0.15 by Till Krüss"
]


p.s. you're missing a ) in the var_dump.

**Comment by tillkruss** [comment]
If you added the action, but no log file is created, then either you need to add it earlier (in a MU-plugin), or something outside of WordPress is flushing your Redis database.

Either way, this seems to be a setup specific issue and not related to this plugin.

**Comment by rwkyyy** [comment]
@tillkruss your suggestion with mu-plugin worked like a charm, the log instantly popped up when using a cache flushing actioin, but it did not show when a new order was added/status changed/etc.

What should i understand from this?

**Comment by tillkruss** [comment]
Can you post the entire backtrace that caused the flush that's unwanted?

**Comment by rwkyyy** [comment]
@tillkruss that's the big wierd thing, there is none when a new order is added to the database, but if I check the storage via ssh, it's empty.

So I guess some external factor, outside WP, clears the Redis cache?

**Comment by tillkruss** [comment]
Maybe. It sounds like a setup issue, no plugin related.
