### ISSUE TITLE
Additional WooCommerce Issue with Redis-Cache & Cache Invalidation

### ISSUE THREAD

**Issue by LukeAbell** [rhubarbgroup/redis-cache#292]
We are experiencing the race conditiion issue as clearly documented in this pull request for WooCommerce - https://github.com/woocommerce/woocommerce/pull/27696

It looks like you [commented on the WP ticket](https://core.trac.wordpress.org/ticket/31245#comment:101) related to the option hash, but it looks like that might have been reverted here: https://github.com/rhubarbgroup/redis-cache/compare/2.0.14...2.0.15

Is there way to avoid this in the redis drop-in? I know that if the pull request is merged, that will help with the WooCommerce specific race condition, but I'm worried about other plugin authors that are doing option updates in a similar way that would trigger it.

Related: https://github.com/rhubarbgroup/redis-cache/issues/58

**Comment by LukeAbell** [comment]
I just tested this pull request and the issue persists https://github.com/rhubarbgroup/redis-cache/pull/282

This might be an option? https://github.com/humanmade/memcache-object-cache/blob/master/object-cache.php#L140 as mentioned in the original ticket https://core.trac.wordpress.org/ticket/31245#comment:81

They have specific logic when dealing with the alloptions option.

**Comment by LukeAbell** [comment]
I replicated the human made drop-in logic and it resolved the issue. I haven't fully tested everything but the race condition no longer happens. 

Here's my branch - https://github.com/blueoceanideas/redis-cache/commit/24fe6f24061ac13867cca555c73a4599588b6083

**Comment by tillkruss** [comment]
Hi @LukeAbell, yeah that's a well-know issue with most object caches.

[Object Cache Pro](https://objectcache.pro) ships with a solution that splits the `alloptions` key into a Redis Hash. If you're running a high traffic store, I'd recommend to consider upgrading, it's exceptionally reliable.

If you want to submit a PR that to this repo and bundle your solution behind a feature flag, I'd be happy to merge it.
