### ISSUE TITLE
WP login fuctioning issue upon enabling redis cache plugin

### ISSUE THREAD

**Issue by wajahat021** [rhubarbgroup/redis-cache#304]
Hi,
I am facing WordPress magic login problem while integrating redis-cache plugin with my redis server. i have separate DBs for all WordPress sites
in my environment. when i open WordPress magic login link or enter username and password manually the page just refresh instead of logging me in
i have already tried by by flushing specific db and also by flushing all dbs by flushall command, still no success although wp login works fine for one time if
i disable redis-cache plugin or removing object-cache.php file.
Details:

**Comment by tillkruss** [comment]
I'd suggest disabling the cache group of "magic login".

**Comment by wajahat021** [comment]
i have deleted magic login plugin but still i can not log in to wordpress by entring username and password manually.

**Comment by tillkruss** [comment]
Have you tried flushing your Redis database?

**Comment by wajahat021** [comment]
yes

**Comment by tillkruss** [comment]
Try disabling all other plugins one by one to see which one is causing it, flush the cache after each action.
