### ISSUE TITLE
lots of warnings in php logs

### ISSUE THREAD

**Issue by fasttrackhost** [rhubarbgroup/redis-cache#305]
Hi, php logs getting too big.

Getting lots of these warnings.

1.
RedisException: read error on connection to 123.123.123.123:6379 in ...\wwwroot\wp-content\object-cache.php:1014

2.
PHP Warning:  array_combine() expects parameter 2 to be array, bool given in ...\wwwroot\wp-content\object-cache.php on line 1482

3.
PHP Warning:  Invalid argument supplied for foreach() in ...\wwwroot\wp-content\object-cache.php on line 1495

Status: Conectado
Client: PhpRedis (v5.1.1)
Drop-in: Valid
Disabled: No
Filesystem: Working
Ping: 1
Errors: []
PhpRedis: 5.1.1
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.4
Plugin Version: 2.0.15
Redis Version: 5.0.10
Multisite: No

**Comment by tillkruss** [comment]
That means your Redis Server isn't available for connections.

However this should be resolved:

https://github.com/rhubarbgroup/redis-cache/blob/3f7dd66cddd0c4316a4ccea0f6ae6c00196a5088/includes/object-cache.php#L1476-L1479

**Comment by fasttrackhost** [comment]
thx for the fast reply. Redis is working, but we are having issues with too many simultaneous connections. Is only trowing this warnings under 1 domain, and strangely it isnt the one with most traffic. This happens while using WP All import plugin for Woocommerce products, with a teribly big amount of records.

**Comment by tillkruss** [comment]
Yes, that's a Redis Server issue, unrelated to this plugin.

**Comment by fasttrackhost** [comment]
Yes, the nr of connections is not a plugin problem, but would be great to get those warnings fixed. Thank you for ur time

**Comment by tillkruss** [comment]
@fasttrackhost: Can you try this fix?

https://github.com/rhubarbgroup/redis-cache/commit/c02266793c692897176362e675efa49c6c6b3953

**Comment by fasttrackhost** [comment]
Ok, the warnings are gone.

**Comment by tillkruss** [comment]
Released in 2.0.16
