### ISSUE TITLE
SUGESTION: 'wp-all-import-pro' SHOULD BE ADDED TO 'WP_REDIS_IGNORED_GROUPS'

### ISSUE THREAD

**Issue by fasttrackhost** [rhubarbgroup/redis-cache#306]
Just a sugestion.

Plugin named: 'wp-all-import-pro' should be added by default to: 'WP_REDIS_IGNORED_GROUPS'

This can make Redis memory usage go insanly high, making the benefit a lot less important compared to the problems it causes.

**Comment by tillkruss** [comment]
We don't add customizations for specific plugins, otherwise we'd have an endless maintenance nightmare 🙂
