### ISSUE TITLE
Redis settings in WordPress config are ignored

### ISSUE THREAD

**Issue by dfateyev** [rhubarbgroup/redis-cache#307]
Tried to install to a WordPress instance by Bitnami, in Kubernetes cluster.
There are some issues: the plugin doesn't respect the Redis cluster settings assigned in WP configuration, and tries to use "127.0.0.1" endpoint instead, exactly as described [here](https://wordpress.org/support/topic/redis-cache-does-not-respect-wp_redis_host/). What can be the issue there?
The Diagnostics output:
```
Status: Not connected
Client: predis
Drop-in: Valid
Disabled: No
Ping: 
Errors: [
    "Connection refused [tcp:\/\/127.0.0.1:6379]"
]
PhpRedis: Not loaded
Predis: 1.1.6
Credis: Not loaded
PHP Version: 7.4.13
Plugin Version: 2.0.17
Redis Version: Unknown
Multisite: No
Filesystem: Working
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_CLIENT: "predis"
WP_REDIS_HOST: "redis-test0-master"
WP_REDIS_PORT: 6379
WP_REDIS_DATABASE: 0
WP_REDIS_MAXTTL: "86400"
WP_REDIS_PASSWORD: ••••••••
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Unflushable Groups: []
Drop-ins: [
    "Redis Object Cache Drop-In v2.0.17 by Till Krüss"
]

```

**Comment by tillkruss** [comment]
What happens when you switch the client to PhpRedis?

**Comment by dfateyev** [comment]
> What happens when you switch the client to PhpRedis?

After switching to "phpredis", the error message changes:
```
Status: Not connected
Client: PhpRedis (v5.3.2)
Drop-in: Valid
Disabled: No
Ping: 
Errors: [
    "Connection refused"
]
PhpRedis: 5.3.2
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.13
Plugin Version: 2.0.17
Redis Version: Unknown
Multisite: No
Filesystem: Working
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_CLIENT: "phpredis"
WP_REDIS_HOST: "redis-test0-master"
WP_REDIS_PORT: 6379
WP_REDIS_DATABASE: 0
WP_REDIS_MAXTTL: "86400"
WP_REDIS_PASSWORD: ••••••••
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Unflushable Groups: []
Drop-ins: [
    "Redis Object Cache Drop-In v2.0.17 by Till Krüss"
]
```

I also don't understand, whether it tries to connect to localhost again, or there is a remote peer connection error.
Accessing Redis from the same Pod via "redis-cli" with the same credentials doesn't produce an error:

```
wordpress-test0-7d6d966bb6-99qnq:/opt/bitnami$ ./redis-cli -h redis-test0-master -a xxxxxxxx
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis-test0-master:6379> info
# Server
<output>

```

**Comment by tillkruss** [comment]
What happens when you do this in a single PHP file?

```
$redis = new Redis;
$redis->connect('redis-test0-master', 6379, 2.0);
var_dump($redis->ping());
```

**Comment by dfateyev** [comment]
The snipped above (w/o authorization) surely fail:
```
[Mon Jan 04 15:53:11.372818 2021] [php7:error] [pid 267] [client 10.239.144.0:38138] PHP Fatal error:  Uncaught RedisException: NOAUTH Authentication required. in /opt/bitnami/wordpress/wp-test.php:4\nStack trace:\n#0 /opt/bitnami/wor │
│ 10.239.144.0 - - [04/Jan/2021:15:53:11 +0000] "GET /wp-test.php HTTP/1.1" 500 18
```
But once I have added the password passing it went without issues:
```
<?php echo '<p>Hello World</p>';
$redis = new Redis;
$redis->connect('redis-test0-master', 6379, 2.0);
$redis->auth('xxxxxxxx');
var_dump($redis->ping());
?>
```
...
```
Hello World
bool(true) 
```

**Comment by tillkruss** [comment]
And the WP plugin still shows "Connection refused"?

**Comment by dfateyev** [comment]
> And the WP plugin still shows "Connection refused"?

Exactly, and I suspect that WP_REDIS_* envs are read, written in the diagnostics output, but not used for the connection. For predis, it's evident (the `"Connection refused [tcp:\/\/127.0.0.1:6379]"` message while different credentials are specified), and probably the same issue with phpredis there.

**Comment by tillkruss** [comment]
In `object-cache.php` can you dump this:

```php
var_dump($parameters);
```

Right after:

```
$client = $this->determine_client();
$parameters = $this->build_parameters();
```

**Comment by dfateyev** [comment]
> In `object-cache.php` can you dump this:
> 
> ```
> var_dump($parameters);
> ```

```
array(7) { ["scheme"]=> string(3) "tcp" ["host"]=> string(9) "127.0.0.1" ["port"]=> int(6379) ["database"]=> int(0) ["timeout"]=> int(1) ["read_timeout"]=> int(1) ["retry_interval"]=> NULL }
Skip to content
```
It definitely looks different to the values reported in "Diagnostics":
```
WP_REDIS_CLIENT: "phpredis"
WP_REDIS_HOST: "redis-test0-master"
WP_REDIS_PORT: 6379
WP_REDIS_DATABASE: 0
WP_REDIS_MAXTTL: "86400"
WP_REDIS_PASSWORD: ••••••••
```

**Comment by tillkruss** [comment]
Are you defining the `WP_REDIS_HOST` at the very top of your config?

**Comment by dfateyev** [comment]
> Are you defining the `WP_REDIS_HOST` at the very top of your config?

Indeed, the problem was I put "WP_REDIS_" settings in the end of the wp-config, so they were nor working.
Moving them to the very beginning made the plugin active.
I haven't tested the overall performance yet (and also the switch to "predis" back), but it's another topic.
Thanks for pointing out on the config options location!

**Comment by soleraeus** [comment]
> Are you defining the `WP_REDIS_HOST` at the very top of your config?

I beg of you, could you please say that IN the man of the plugin? That would save developers a lot of time. Had to go through the code in object-cache.php and manipulate the functions to retrace call orders and understand the issue was my host was not defined yet when this file is called. Which by the way is not an issue for wp-cli nor for the basic test script since the full config is already loaded. I highly suspect most people having issues have made the mistake of appending definitions instead of putting them at the very top.

**Comment by tillkruss** [comment]
You're welcome to open a PR with the extended instructions.
