### ISSUE TITLE
Removing Redis cache plugin improved my website speed by 50%

### ISSUE THREAD

**Issue by rvencu** [rhubarbgroup/redis-cache#310]
I have a transactional website where I use a lot of Formidable Forms forms, views, etc.

I started profiling it and had the surprise that Redis was taking most of the resources. Finally, when I removed the plugin, I got a lot of performance improvement in all areas, of course not on MySQL side. But the benefits heavily overcame the loss on the database side. I present a delta report below.

Now, I read that PHP is always single-threaded and most calls to Redis are not pipelined. I saw 4x to 9x improvements on articles just by adding the pipeline() method.

So, I am asking, what kind of strategy should be applied in this scenario? How can I separate transactional calls from counters and more general database calls like getting the options from the DB? Or otherwise put, how can I let formidable forms plugins skip Redis completely but other parts of the website still use it instead?

![image](https://user-images.githubusercontent.com/287411/106254978-0bb8c280-6222-11eb-9107-d916d87682f7.png)

At the network benchmark, things improved down from 99.7MB to 68B !!! This is why it shows -100%...

**Comment by tillkruss** [comment]
WordPress can't use pipelines, with the exception of Object Cache Pro's prefetching feature. 

If your site slows down with Redis, then your Redis Server is likely misconfigured. 

Can you post your Redis Server stats, such as memory pressure and req/s?

**Comment by rvencu** [comment]
This could be. I installed the stable version with make command into a Centos 7 server.

I am posting info here about the installation. Did a fresh update, I will reinstall the plugin into the staging app and run the profile again, then extract the stats.

Until ready this is the server info:

redis-cli INFO #redis-server version
# Server
redis_version:6.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:58b07357c25a3ec0
redis_mode:standalone
os:Linux 3.10.0-1160.11.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.1
process_id:589
run_id:56c432c3f6555ef8762daaa0d28cb36adb8a83ce
tcp_port:6379
uptime_in_seconds:38
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:1339846
executable:/usr/local/bin/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:1
client_recent_max_input_buffer:327680
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1701008
used_memory_human:1.62M
used_memory_rss:12722176
used_memory_rss_human:12.13M
used_memory_peak:2027728
used_memory_peak_human:1.93M
used_memory_peak_perc:83.89%
used_memory_overhead:858752
used_memory_startup:840232
used_memory_dataset:842256
used_memory_dataset_perc:97.85%
allocator_allocated:2139904
allocator_active:2453504
allocator_resident:8495104
total_system_memory:67340754944
total_system_memory_human:62.72G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.15
allocator_frag_bytes:313600
allocator_rss_ratio:3.46
allocator_rss_bytes:6041600
rss_overhead_ratio:1.50
rss_overhead_bytes:4227072
mem_fragmentation_ratio:7.77
mem_fragmentation_bytes:11084624
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:383
rdb_bgsave_in_progress:0
rdb_last_save_time:1611952544
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:5
total_commands_processed:852
instantaneous_ops_per_sec:0
total_net_input_bytes:753679
total_net_output_bytes:821544
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:273
keyspace_misses:290
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_reads_processed:885
total_writes_processed:852
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_replid:55debe90f5b2afb3624380b16d9272065460c9bd
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.078718
used_cpu_user:0.051790
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules
module:name=ft,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=335,expires=32,avg_ttl=14304307

**Comment by tillkruss** [comment]
With `instantaneous_ops_per_sec` being `0`, I take it your server is misconfigured, rather than a load issue. I'd suggest asking your hosting provider for assistance with configuring Redis Server.

**Comment by rvencu** [comment]
Nope, this was just the info after update and service restart

This is after 10 minutes in production

redis-cli INFO #redis-server version
# Server
redis_version:6.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:58b07357c25a3ec0
redis_mode:standalone
os:Linux 3.10.0-1160.11.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.1
process_id:589
run_id:56c432c3f6555ef8762daaa0d28cb36adb8a83ce
tcp_port:6379
uptime_in_seconds:1030
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:1340838
executable:/usr/local/bin/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:2
client_recent_max_input_buffer:917574
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:34919192
used_memory_human:33.30M
used_memory_rss:52617216
used_memory_rss_human:50.18M
used_memory_peak:52731552
used_memory_peak_human:50.29M
used_memory_peak_perc:66.22%
used_memory_overhead:2081512
used_memory_startup:840232
used_memory_dataset:32837680
used_memory_dataset_perc:96.36%
allocator_allocated:34904824
allocator_active:37089280
allocator_resident:54833152
total_system_memory:67340754944
total_system_memory_human:62.72G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.06
allocator_frag_bytes:2184456
allocator_rss_ratio:1.48
allocator_rss_bytes:17743872
rss_overhead_ratio:0.96
rss_overhead_bytes:-2215936
mem_fragmentation_ratio:1.51
mem_fragmentation_bytes:17762416
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:413728
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:891816
rdb_bgsave_in_progress:0
rdb_last_save_time:1611952544
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:321
total_commands_processed:926889
instantaneous_ops_per_sec:686
total_net_input_bytes:16169397839
total_net_output_bytes:321668677
instantaneous_input_kbps:10673.77
instantaneous_output_kbps:3.35
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:2454
expired_stale_perc:0.13
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:83
evicted_keys:0
keyspace_hits:27582
keyspace_misses:9011
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_reads_processed:1808031
total_writes_processed:926896
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_replid:55debe90f5b2afb3624380b16d9272065460c9bd
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:78.766026
used_cpu_user:24.977758
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules
module:name=ft,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=11783,expires=6651,avg_ttl=1829697
[root@webtop redis-6.0.10]# redis-cli INFO #redis-server version
# Server
redis_version:6.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:58b07357c25a3ec0
redis_mode:standalone
os:Linux 3.10.0-1160.11.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.1
process_id:589
run_id:56c432c3f6555ef8762daaa0d28cb36adb8a83ce
tcp_port:6379
uptime_in_seconds:1190
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:1340998
executable:/usr/local/bin/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:2
client_recent_max_input_buffer:393286
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:47576008
used_memory_human:45.37M
used_memory_rss:60399616
used_memory_rss_human:57.60M
used_memory_peak:52908920
used_memory_peak_human:50.46M
used_memory_peak_perc:89.92%
used_memory_overhead:2181206
used_memory_startup:840232
used_memory_dataset:45394802
used_memory_dataset_perc:97.13%
allocator_allocated:47575712
allocator_active:48996352
allocator_resident:57135104
total_system_memory:67340754944
total_system_memory_human:62.72G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.03
allocator_frag_bytes:1420640
allocator_rss_ratio:1.17
allocator_rss_bytes:8138752
rss_overhead_ratio:1.06
rss_overhead_bytes:3264512
mem_fragmentation_ratio:1.27
mem_fragmentation_bytes:12886936
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:413798
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1040715
rdb_bgsave_in_progress:0
rdb_last_save_time:1611952544
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:368
total_commands_processed:1082248
instantaneous_ops_per_sec:662
total_net_input_bytes:20156788161
total_net_output_bytes:390616403
instantaneous_input_kbps:5681.38
instantaneous_output_kbps:8.49
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:2579
expired_stale_perc:0.01
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:99
evicted_keys:0
keyspace_hits:32306
keyspace_misses:10900
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_reads_processed:2189551
total_writes_processed:1082256
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_replid:55debe90f5b2afb3624380b16d9272065460c9bd
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:93.009644
used_cpu_user:29.949988
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules
module:name=ft,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=13448,expires=8027,avg_ttl=1438294

**Comment by tillkruss** [comment]
If your CPU is at 93%, I'd move Redis onto a dedicated machine.

**Comment by rvencu** [comment]
Scratching my head here. My system has 22 procs. I am sure Redis is using another proc than the PHP since the overall load was between 1 and 2 procs. This core is 2.4GHz let say I move to a dedicated server with 4GHz core, Redis will only use one core and it would improve processor speed 3x or 4x?

I do not see a solution in that. My app is simply throwing (perhaps) too many queries on it. For the above numbers, I only loaded one page twice.

I also wonder, for a 3MB page, why Redis ingested 20GB of data then spit back 4GB? For this amount of data is no wonder the single-core it uses goes up to 93% load...

**Comment by rvencu** [comment]
I did an experiment with Memcached, it is 3 times worse than with Redis... so I guess, it is not a problem of Redis server configuration as much as this use case is not really recommended for caching...

**Comment by tillkruss** [comment]
Maybe try a vanilla WP install without any plugins, and see if that runs as expected.

**Comment by paulocoghi** [comment]
I suggest to reopen this issue because I am getting worse performance with Redis Object Cache. I can provide more details, if it's requested.

**Comment by tillkruss** [comment]
@paulocoghi: Feel free to open a new issue with your benchmark and reports.
