### ISSUE TITLE
Redis cache + WooCommerce = ghost orders

### ISSUE THREAD

**Issue by r007** [rhubarbgroup/redis-cache#312]
Hi guys,

After migration of our server from WPEngine to AWS, I installed nginx with FastCGI cache + Redis cache (see https://www.soar.sh/). Everything was fine, no errors or anything. But then a customer came in and complained about the order:

1. He successfully makes a purchase.
2. He gets a email "thanks for your order #166025" (which is strange, because this order number is not the latest one, it lags behind by a few days, the latest number is like #166520)
3. The order itself is not registered on WooCommerce dashboard, but can be seen in stripe payment system. So the payment was successfully processed.
4. Also he can see his order on /my-account page. But we can't. When we try to open that order, we see another name.
5. When we disable redis cache, all these "ghost" orders with weird numbers are gone. After disabling, everything is functioning as usual and we can see his orders again.
6. After disabling cache he gets logged out immediately.

There are no errors or anything. Seems like a bug or something. Plus, it affects only the small amount of people (not everyone).

**Comment by tillkruss** [comment]
Hi @r007: The OSS version can be (at times) be a little unreliable, compared to the [Pro version](https://objectcache.pro) which was specifically built for WooCommerce stores needing reliability.

I can't tell you whether this is a bug in WooCommerce, a 3rd party plugin interfering with WC, or a bug in this plugin, sorry.

**Comment by r007** [comment]
@tillkruss Alright, understood, thanks!
