### ISSUE TITLE
#Enhancement could you try tarantool object cache for.WordPress as plugin and switchable between redis 

### ISSUE THREAD

**Issue by osevan** [rhubarbgroup/redis-cache#313]
https://github.com/tarantool/tarantool-php

Maybe you can plant this in cache plugin, because its faster.than redis .

Thanks and

Best regards

**Comment by tillkruss** [comment]
@osevan hey! Are you up for making a PR?

**Comment by osevan** [comment]
> @osevan hey! Are you up for making a PR?

Ofc not, I want inform you about newest databases for object cache backend addition

**Comment by tillkruss** [comment]
No plans to add support.
