### ISSUE TITLE
WP_REDIS_PREFIX is not actually used to prefix all keys in all operations?

### ISSUE THREAD

**Issue by meglio** [rhubarbgroup/redis-cache#318]
In order to employ the new Redis ACL and share the same Redis instance between multiple WordPress instances, it would make sense to allow only certain prefixes per Redis ACL user. It is not clear, however, how to make `redis-cache` prefix ALL keys for all cache operations.

I do see there is a `WP_REDIS_PREFIX` constant, however, it looks like it is only used for `flush` commands and not to force-prefix all keys in all operations.

Could you please clarify on this.
-- Many thanks, Anton

**Comment by naxvog** [comment]
The prefix is also used in the `build_key` method: https://github.com/rhubarbgroup/redis-cache/blob/918c4b45ef6d278318809ba90d3979b5a3ed25b7/includes/object-cache.php#L1778

**Comment by tillkruss** [comment]
Hi Anton,

First of all, I always recommend using different databases to separate tenants. You can bump the count from `16` to whatever you like using the `databases` option in your `redis.conf`. The reason for that is that flushing based on prefix using `SCAN` is incredibly inefficient.

However, if you set `WP_REDIS_PREFIX` and `WP_REDIS_SELECTIVE_FLUSH` then WordPress won't touch other prefixes and you can use the Redis `ACL` command to set up your different users. You can connect setting `WP_REDIS_PASSWORD` to an array `['username', 'password']`.

**Comment by meglio** [comment]
Hi @tillkruss, you might want to read this discussion at Stackoverflow: [What's the Point of Multiple Redis Databases?](https://stackoverflow.com/questions/16221563/whats-the-point-of-multiple-redis-databases) 

The key point is (citing):

> Even Salvatore Sanfilippo (creator of Redis) thinks it's a bad idea to use multiple DBs in Redis. See his comment here:
> https://groups.google.com/d/topic/redis-db/vS5wX8X4Cjg/discussion
>> I understand how this can be useful, but unfortunately I consider Redis multiple database errors my worst decision in Redis design at all... without any kind of real gain, it makes the internals a lot more complex. The reality is that databases don't scale well for a number of reason, like active expire of keys and VM. If the DB selection can be performed with a string I can see this feature being used as a scalable O(1) dictionary layer, that instead it is not.
>> With DB numbers, with a default of a few DBs, we are communication better what this feature is and how can be used I think. I hope that at some point we can drop the multiple DBs support at all, but I think it is probably too late as there is a number of people relying on this feature for their work.


-----

> However, if you set WP_REDIS_PREFIX and WP_REDIS_SELECTIVE_FLUSH then WordPress won't touch other prefixes and you can use the Redis ACL command to set up your different users.

While this is exactly how I understood it, I could not locate the piece of code that does that. Could you possibly point out? Many thanks.

**Comment by tillkruss** [comment]
Yes, while that's true, he's talking about an ideal setup/scenario, which in the case of messy WordPress is: A single Redis Server/Cluster per site. That way you don't have multiple applications competing for single-threaded Redis.

If you find yourself in a messy situation, the 2nd best option is different databases, IMO. 

You can read more about those options here: https://github.com/rhubarbgroup/redis-cache/wiki/Configuration-Options

**Comment by meglio** [comment]
Thanks @tillkruss, what about the other question in my message? I scanned the plugin for `WP_REDIS_PREFIX` and could not locate the code responsible for prefixing **all** Redis commands. I could only locate the code that prefixes the flush.
