### ISSUE TITLE
Set custom value for WP_REDIS_DATABASE 

### ISSUE THREAD

**Issue by ljfreelancer88** [rhubarbgroup/redis-cache#319]
For `WP_REDIS_DATABASE` value,  is it possible to put a domain but it's "encoded" to integer value, instead of setting it using `0`, `1`... Because the problem is when you have multiple sites, I should have to remember the last value for `WP_REDIS_DATABASE` so that it won't coalite.

**Comment by tillkruss** [comment]
No, you'll have to maintain your own domain to database map. I personally use environment variables.
