### ISSUE TITLE
Plugin doesn't support user/password authentication

### ISSUE THREAD

**Issue by Kadigan** [rhubarbgroup/redis-cache#321]
I'm having trouble using this plugin. From my host, I've been given: IP, Port, Database name, User name, Password.

This plugin doesn't seem to have any field for "Database name" (only integer ID, which may or may not be relevant), nor "User name".

Attempting to connect without it results in "NOAUTH Authentication Required".

**Comment by tillkruss** [comment]
Yes it does. Check the README or the Wiki on this repository.
