### ISSUE TITLE
Cache flush & partially flush

### ISSUE THREAD

**Issue by DangerD1024** [rhubarbgroup/redis-cache#322]
The main problem when i click flush cache it cleares whole redis database which is also used by another functions
Another feature request if to flush cache partially for example for post id or user id. I have custom query that removes user meta that contains serialized array (using delete_user_meta i'm unable to detele that)

**Comment by tillkruss** [comment]
I'd recommend using a different database index for other datasets. If you can't do that, you could use the selective flushing: https://github.com/rhubarbgroup/redis-cache/wiki/Configuration-Options
