### ISSUE TITLE
The `decr()` method is missing

### ISSUE THREAD

**Issue by johnbillion** [rhubarbgroup/redis-cache#327]
The `wp_cache_decr()` function calls `$wp_object_cache->decr()`, but this method is missing from the `WP_Object_Cache` class. The `decrement()` method exists, as does `increment()` and `incr()`.

**Comment by tillkruss** [comment]
Odd, I guess nobody has been calling this directly ever. I added an alias in 2b7f711. Is that sufficient for you?

**Comment by johnbillion** [comment]
Looks good, works the same as `incr()` 👍

**Comment by tillkruss** [comment]
Closed in 2b7f71178b578ae9b2abbcaedbfc1ba6b2a577ed.
