### ISSUE TITLE
Cannot redeclare wp_cache_add()

### ISSUE THREAD

**Issue by sjoukedv** [rhubarbgroup/redis-cache#334]
Hi,

The drop-in is throwing a fatal error;

```
PHP Fatal error: Cannot redeclare wp_cache_add()
(previously declared in /<path>/public/wp-content/object-cache.php:33) in /<path>/public/wp-includes/cache.php on line 30" 
```

The `wp_cache_add()` function is not mentioned in the [pluggable](https://codex.wordpress.org/Pluggable_Functions) functions. Nevertheless, several Redis plugins override this function (and it's siblings) inside a drop-in.

All help is appreciated!

**Comment by tillkruss** [comment]
Hey @sjoukedv,

try deleting the drop-in and disabling all caching plugins and then setting up Redis Object Cache again.

**Comment by sjoukedv** [comment]
Thanks, this helped me locate the issue inside the `mu-plugins` directory, specifically including `wp-includes/cache.php` there.

**Comment by tillkruss** [comment]
Ah, good to know!
