### ISSUE TITLE
WP_REDIS_DISABLE_COMMENT does not take effect

### ISSUE THREAD

**Issue by faganer** [rhubarbgroup/redis-cache#341]
I want to remove:
```
Performance optimized by Redis Object Cache. Learn more: https://wprediscache.com

Retrieved 3665 objects (31 KB) from Redis using Predis (v1.1.9).
```
It's now set up:
```
define('WP_REDIS_CONFIG', [
	'WP_REDIS_DISABLE_COMMENT' => true,
]);
```
[https://github.com/rhubarbgroup/redis-cache/wiki/Configuration-Options#wp_redis_disable_comment-default-not-set](https://github.com/rhubarbgroup/redis-cache/wiki/Configuration-Options#wp_redis_disable_comment-default-not-set)

But it doesn't take effect, am I setting it wrong? What should be the correct setting?

**Comment by tillkruss** [comment]
`WP_REDIS_CONFIG` is for the Pro version only.
