### ISSUE TITLE
Notice: Undefined offset: 1 in plugins/redis-cache/dependencies/predis/predis/src/Command/ServerInfo.php on line 58

### ISSUE THREAD

**Issue by AfanasievAM** [rhubarbgroup/redis-cache#343]
WordPress site using your plugin, latest version.
When connecting to CloudRun Redis gives an error, although everything works.

**Notice**
Notice: Undefined offset: 1 in /var/www/html/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Command/ServerInfo.php on line 58

**Overview**

```
Status: Connected
Drop-in: Valid
Filesystem: Writeable
Connection
Client: Predis (v1.1.9)
Host: 10.210.183.60
Port: 6379
Database: 0
Connection Timeout: 1s
Read Timeout: 1s
Redis Version: 5.0.12
```

**Diagnostic**

```
Notice:  Undefined offset: 1 in /var/www/html/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Command/ServerInfo.php on line 58

Status: Connected
Client: Predis (v1.1.9)
Drop-in: Valid
Disabled: No
Ping: PONG
Errors: []
PhpRedis: Not loaded
Relay: Not loaded
Predis: 1.1.9
Credis: Not loaded
PHP Version: 7.4.28
Plugin Version: 2.0.23
Redis Version: 5.0.12
Multisite: No
Metrics: Enabled
Metrics recorded: 62
Filesystem: Working
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_HOST: "10.210.183.60"
WP_REDIS_PORT: "6379"
WP_REDIS_DATABASE: 0
WP_REDIS_TIMEOUT: 1
WP_REDIS_READ_TIMEOUT: 1
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes",
    "WPML_ST_Package_Factory"
]
Unflushable Groups: []
Drop-ins: [
    "advanced-cache.php v by ",
    "Redis Object Cache Drop-In v2.0.23 by Till Krüss"
]

```

**Comment by tillkruss** [comment]
Can you try installing the version from `develop` from this repo? That has Predis v1.10.0, which may resolve the issue.

**Comment by AfanasievAM** [comment]
Is it enough to update predis to v1.10.0?
Or does the whole plugin need to be updated?

**Comment by tillkruss** [comment]
If you can run a composer update, yes that's enough.

**Comment by AfanasievAM** [comment]
where can I download a ready-made plugin from the development branch?
I'm afraid in my current infrastructure I can't make such an upgrade.

**Comment by AfanasievAM** [comment]
Status: Not connected
Client: 
Drop-in: Valid
Disabled: No
Ping: 
**Connection Exception: Predis library not found. Re-install Redis Cache plugin or delete the object-cache.php. (Exception)
Errors: [
    "Predis library not found. Re-install Redis Cache plugin or delete the object-cache.php."
]**
PhpRedis: Not loaded
Relay: Not loaded
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.28
Plugin Version: 2.0.24-dev
Redis Version: Unknown
Multisite: No
Metrics: Disabled
Metrics recorded: null
Filesystem: Working
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_HOST: "10.210.183.60"
WP_REDIS_PORT: "6379"
WP_REDIS_DATABASE: 0
WP_REDIS_TIMEOUT: 1
WP_REDIS_READ_TIMEOUT: 1
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta",
    "WPML_ST_Package_Factory"
]
Unflushable Groups: []
Drop-ins: [
    "advanced-cache.php v by ",
    "Redis Object Cache Drop-In v2.0.24-dev by Till Krüss"
]

**Comment by AfanasievAM** [comment]
Plugin Version: 2.0.24-dev
