### ISSUE TITLE
Slow time on return data from Redis

### ISSUE THREAD

**Issue by elvishp2006** [rhubarbgroup/redis-cache#344]
I'm getting slow time on return data from Redis on my infra, this can be a plugin issue, or a thing that I can improve on my Redis server?
![Captura de Tela 2022-04-04 às 12 07 55](https://user-images.githubusercontent.com/7463100/161574206-90e24ce6-e72d-4c6e-8439-364862a6a0a9.png)
![Captura de Tela 2022-04-04 às 12 08 08](https://user-images.githubusercontent.com/7463100/161574241-c7c254dc-b251-4f9f-95ba-8e6d6ffa44cd.png)
![Captura de Tela 2022-04-04 às 12 08 30](https://user-images.githubusercontent.com/7463100/161574310-bd05e4d5-548f-4d2e-bc92-e4d53906c40f.png)
![Captura de Tela 2022-04-04 às 12 08 41](https://user-images.githubusercontent.com/7463100/161574337-27c7e34b-6062-49c9-a5bd-4d714970e04d.png)

```
Status: Conectado
Client: PhpRedis (v5.3.6)
Drop-in: Valid
Disabled: No
Ping: 1
Errors: []
PhpRedis: 5.3.6
Relay: Not loaded
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.4.27
Plugin Version: 2.0.23
Redis Version: 5.0.6
Multisite: Yes
Metrics: Enabled
Metrics recorded: 2660
Filesystem: Não foi possível inicializar o sistema de arquivos.
Global Prefix: ""
Blog Prefix: 1
WP_REDIS_HOST: "example.nkqmrl.ng.0001.use1.cache.amazonaws.com"
WP_REDIS_PORT: "6379"
WP_REDIS_DATABASE: "0"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Drop-ins: [
    "Redis Object Cache Drop-In v2.0.23 by Till Krüss"
]
```

# Server
redis_version:5.0.6
redis_git_sha1:0
redis_git_dirty:0
redis_build_id:0
redis_mode:standalone
os:Amazon ElastiCache
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:0.0.0
process_id:1
run_id:b44662e4df1808709d949e4b808ed42ea37d0b8e
tcp_port:6379
uptime_in_seconds:1044800
uptime_in_days:12
hz:10
configured_hz:10
lru_clock:4917411
executable:-
config_file:-

# Clients
connected_clients:3
client_recent_max_input_buffer:26585500
client_recent_max_output_buffer:29360152
blocked_clients:0

# Memory
used_memory:429443320
used_memory_human:409.55M
used_memory_rss:554704896
used_memory_rss_human:529.01M
used_memory_peak:756318176
used_memory_peak_human:721.28M
used_memory_peak_perc:56.78%
used_memory_overhead:28024812
used_memory_startup:3346192
used_memory_dataset:401418508
used_memory_dataset_perc:94.21%
allocator_allocated:430108120
allocator_active:480063488
allocator_resident:597983232
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:2488396677
maxmemory_human:2.32G
maxmemory_policy:volatile-lru
allocator_frag_ratio:1.12
allocator_frag_bytes:49955368
allocator_rss_ratio:1.25
allocator_rss_bytes:117919744
rss_overhead_ratio:0.93
rss_overhead_bytes:-43278336
mem_fragmentation_ratio:1.29
mem_fragmentation_bytes:125303448
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:17130
mem_clients_normal:84162
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:14437274
rdb_bgsave_in_progress:0
rdb_last_save_time:1648039779
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:1339392
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:645981
total_commands_processed:91622916
instantaneous_ops_per_sec:17
total_net_input_bytes:7731161098585
total_net_output_bytes:15969750920051
instantaneous_input_kbps:139.23
instantaneous_output_kbps:285.43
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:1
expired_keys:2858187
expired_stale_perc:0.38
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:57101668
keyspace_misses:16238287
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:472
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:1
slave0:ip=10.31.1.49,port=6379,state=online,offset=7726360487332,lag=0
master_replid:7d7c06e030a8ef7a64e4e90ff3d7a41cfdffcd57
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:7726360487332
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:7726359438757
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:16009.195784
used_cpu_user:9235.982521
used_cpu_sys_children:0.000000
used_cpu_user_children:0.078976

# SSL
ssl_enabled:no
ssl_connections_to_previous_certificate:0
ssl_connections_to_current_certificate:0
ssl_current_certificate_not_before_date:(null)
ssl_current_certificate_not_after_date:(null)
ssl_current_certificate_serial:0

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=232892,expires=61633,avg_ttl=58475854
db1:keys=62609,expires=757,avg_ttl=302243506

**Comment by tillkruss** [comment]
Yes, that seems to be an issue with your AWS Redis Server being very slow, or too far away from your web servers.
