### ISSUE TITLE
counts group cannot be removed from ignored groups

### ISSUE THREAD

**Issue by lots0logs** [rhubarbgroup/redis-cache#346]
For details see: 

*  #114
* #74
* https://core.trac.wordpress.org/ticket/47884#ticket

I've created a PR that addresses the issue in this plugin as was advised by WP Core team in the above linked trac ticket.

**Comment by tillkruss** [comment]
@lots0logs: This is currently discussed in:

- https://github.com/WordPress/performance/issues/76
- https://github.com/WordPress/wordpress-develop/pull/2149

If this is urgent for you, we can copy what @JanThiel did and port it over.

**Comment by lots0logs** [comment]
Thanks, I missed that. I've already deployed a patched copy of the drop-in file with the changes in my PR. It's working so I guess I will keep it until WP core releases their official fix for this issue. Based on my own past experience of getting small fixes actually merged into core it's likely to be a while before we see it merged :roll_eyes: lol
