### ISSUE TITLE
Deprecation notice with PHP 8.1

### ISSUE THREAD

**Issue by nickchomey** [rhubarbgroup/redis-cache#350]
PHP Deprecated:  Redis::connect(): Passing null to parameter 2 ($port) of type int is deprecated in /wp-content/object-cache.php on line 700

It comes from setting port to null just above it. 
```
if (strcasecmp('unix', $parameters['scheme']) === 0) {
    $args['host'] = $parameters['path'];
    $args['port'] = null;
}
```
I'm not smart enough to know how to fix this. 

https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg

**Comment by tillkruss** [comment]
Closed in b3b720c.
