### ISSUE TITLE
Incompatibility with The Events Calendar

### ISSUE THREAD

**Issue by kevinlisota** [rhubarbgroup/redis-cache#351]
Our site runs The Events Calendar from Tribe. Specifically, we run The Events Calendar, Events Calendar Pro and Community Events.

When this Redis object cache is active, it throws a fatal error. I'm not sure if this is the only instance, but we see it on the Community Events public submission form, giving the following stack trace.
```
NOTICE: PHP message: PHP Fatal error: Uncaught TypeError: Tribe\\Utils\\Lazy_String::__toString(): Return value must be of type string, null returned in /var/www/mysite.com/wp-content/plugins/the-events-calendar/common/src/Tribe/Utils/Lazy_String.php:78\n
#0 /var/www/mysite.com/wp-content/plugins/the-events-calendar/common/src/Tribe/Utils/Lazy_String.php(117): Tribe\\Utils\\Lazy_String->__toString()\n
#1 [internal function]: Tribe\\Utils\\Lazy_String->serialize()\n
#2 /var/www/mysite.com/wp-content/object-cache.php(2245): serialize(Object(WP_Post))\n
#3 [internal function]: WP_Object_Cache->{closure}(Object(WP_Post))\n
#4 /var/www/mysite.com/wp-content/object-cache.php(2247): array_map(Object(Closure), Array)\n
#5 /var/www/mysite.com/wp-content/plugins/redis-cache/includes/class-metrics.php(147): WP_Object_Cache->info()\n
#6 /var/www/mysite.com/wp-content/plugins/redis-cache/includes/class-metrics.php(137): Rhubarb\\RedisCache\\Metrics->collect()\n
#7 /var/www/mysite.com/wp-includes/class-wp-hook.php(307): Rhubarb\\RedisCache\\Metrics::record('')\n
#8 /var/www/mysite.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n
#9 /var/www/mysite.com/wp-includes/plugin.php(476): WP_Hook->do_action(Array)\n
#10 /var/www/mysite.com/wp-includes/load.php(1102): do_action('shutdown')\n
#11 [internal function]: shutdown_action_hook()\n
```
I know that there was a similar, though different, [bug before](https://github.com/rhubarbgroup/redis-cache/issues/270), that looks like it was resolved.

In this case, when the Redis object cache is active, the fatal error is thrown. When I put `tribe-events` as an ignored group in Redis, then the Events Calendar works fine, though ignoring from the object cache is not the preferred solution.

I'm uncertain if this is a bug in redis-cache, or if this is something Tribe needs to resolve.

**Comment by tillkruss** [comment]
It's up "The Events Calendar" the handle types.

**Comment by bozzmedia** [comment]
Just popping by to say the TEC devs have acknowledge the ongoing incompatibility with redis object cache. Unfortunately they have not prioritized a fix for it as of Sept 2022.

**Comment by tillkruss** [comment]
WordPress 6.1 will promote using an object cache, they better get this fixed 😓
