### ISSUE TITLE
fputcsv adding metric data to output csv

### ISSUE THREAD

**Issue by MrHappyAsh** [rhubarbgroup/redis-cache#356]
I'm currently using a function to output data from an array to a csv file. This was fine until a recent update(unsure which), now the output csv has some metric data from object cache pro.

I have checked the array being input into this function and it's all good. So whatever is happening, is happening here.

Plugin version: Object Cache Pro 1.15.2

My function:

```
function export_orders_csv($data) {
	ob_clean();
	ob_start();
	header('Content-Type: application/octet-stream');
	header('Content-Disposition: attachment; filename=export.csv');

	$outFile = fopen('php://output', "w") or die("Unable to open file!");

	$csv_headers = array('order_id', 'order_status', 'order_date', 'product_id', 'product_name', 'quantity_sold', 'line_total', 'quantity_refunded',  'refunded_total', 'site_fees', 'net_quantity', 'rep_total', 'discount_total', 'first_name', 'last_name', 'email', 'phone', 'attending_to_see');

	fputcsv($outFile, $csv_headers);

	foreach($data as $order){
		foreach ($order as $value) {
			fputcsv($outFile, $value);
		}
	}
	
	fclose($outFile);
	ob_end_flush();
	exit();
}
```

Row appended to the csv output:
`<!-- plugin=object-cache-pro client=phpredis metric#hits=4944 metric#misses=51 metric#hit-ratio=99.0 metric#bytes=1769028 metric#prefetches= metric#store-reads=193 metric#store-writes=8 metric#store-hits=152 metric#store-misses=41 metric#ms-total=7247.26 metric#ms-cache=48.26 metric#ms-cache-median=0.22 metric#ms-cache-ratio=0.7 -->`

csv example:
![image](https://user-images.githubusercontent.com/20417550/177144085-1a72f3bc-1ff7-4dba-9a62-349998e3db03.png)

**Comment by tillkruss** [comment]
Shoot use a message at https://objectcache.pro/support
