### ISSUE TITLE
[Suggestion] Symlink the drop-in file instead of copying it

### ISSUE THREAD

**Issue by zaherg** [rhubarbgroup/redis-cache#359]
Currently, the plugin will copy the file to its correct location and whenever needed it will prompt the user to update the drop-in file, I was wondering if there is any technical matter which prevent us from creating a symlink instead (like how the query monitor symlink their `db.php` file).

by having a symlink, we can remove the `maybe_update_dropin` action.

In my local dev environment, I couldn't notice any difference between having a symlink or a copy (I use symlink since my code was already outside wp directory).

This is a low priority change, and can be discussed later nothing urgent.

**Comment by tillkruss** [comment]
Too risky. Better to improve safe, automatic updates to the file.
