### ISSUE TITLE
Minor issue with get_multiple()

### ISSUE THREAD

**Issue by igitabout** [rhubarbgroup/redis-cache#368]
In:
https://github.com/rhubarbgroup/redis-cache/blob/efec7050b30cda56459517e67e4294714e3c3a35/includes/object-cache.php#L1838-L1851

Shouldn't `$cache[ $key ] = $value;` be in the else statement?

```
                } else {
                    $cache[ $key ] = $value;
                    $this->cache_hits++;
                }
```

**Comment by tillkruss** [comment]
Mhhh, no we need to return a an array with all keys, and if it's not in the cache it would indicate `false`.
