### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by szepeviktor** [rhubarbgroup/redis-cache#369]
`$args = is_predis()`

Does PHPStan spot this?

**Comment by szepeviktor** [comment]
We do not use PHPStan :(
https://github.com/rhubarbgroup/redis-cache/blob/f9c4162558fd237425066b93214fde3817fb7bcb/composer.json#L21-L35

**Comment by tillkruss** [comment]
@zaherg: Wanna set up low level phpstan?

**Comment by szepeviktor** [comment]
@zaherg There are forgotten seeds in https://github.com/rhubarbgroup/redis-cache/pull/298

**Comment by tillkruss** [comment]
@zaherg: Let's run these in GHA as well.

**Comment by szepeviktor** [comment]
There is at least one grave error: includes/class-plugin.php:207
https://developer.wordpress.org/reference/functions/wp_add_dashboard_widget/

**Comment by zaherg** [comment]
@tillkruss @szepeviktor sure thing, it look like it slipped out when I was working on the local setup.

I'll open a PR soon and hopefully @szepeviktor can help guiding me to complete it.

@tillkruss should I create a separate GHA file for it call it `phpstan.yml` or just add it to the current one?
