### ISSUE TITLE
Is there a limit to the number of databases?

### ISSUE THREAD

**Issue by joelataylor** [rhubarbgroup/redis-cache#375]
Hi there! Love the plugin, but have a question on the `WP_REDIS_DATABASE` setting. Is there a limit to this field?
I've found that when this global variable is set to > 20 I'm getting cache returned from other sites. Obviously they're all using the same redis instance.

Thoughts?

**Comment by tillkruss** [comment]
Not really, it depends on your `databases` setting in your `redis.conf`.

**Comment by petertwise** [comment]
Thanks! This is super helpful. I added this info to the Wiki.
