### ISSUE TITLE
Issue with WP_REDIS_GRACEFUL

### ISSUE THREAD

**Issue by ffxluca** [rhubarbgroup/redis-cache#386]
I have one issue with `WP_REDIS_GRACEFUL`

WordPress makes several calls to `wp_cache_delete()` (especially [wp-includes/meta.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/meta.php) ): if one of them ends up being a no-op, the relevant cache entry becomes stale. WordPress eventually will re-connect to Redis, and that will respond with a cache hit instead of a cache miss.

Note it is borderline impossible to replicate this behaviour unless the Redis server is hosted on a different machine rather than the one where WordPress runs (with php-fpm, in my case).

**Comment by tillkruss** [comment]
Any suggestions on how to improve this?

I actually lean towards removing it entirely because it prompts the cache being out of sync.
