### ISSUE TITLE
Support for ENV variables as configuration

### ISSUE THREAD

**Issue by jordy758** [rhubarbgroup/redis-cache#400]
Hi guys,

It would be nice if we could set configuration settings through environment variables (retrieved through ```getenv()```). This way we can support dockerized containers that use environment variables which discards the need to change anything in the wp_config.php itself.

**Comment by tillkruss** [comment]
You can already do that, you just have to set the constants in your config from environment variables. 


```php
define('WP_REDIS_HOST', getenv('REDIS_HOST'));

define('WP_REDIS_PORT', getenv('REDIS_PORT'));
```

And so on.
