### ISSUE TITLE
connecting via unix socket requires both WP_REDIS_HOST and WP_REDIS_PATH to be defined

### ISSUE THREAD

**Issue by karock** [rhubarbgroup/redis-cache#403]
tried to connect over a unix socket file and it was continuing to default to 127.0.0.1 when I only defined `WP_REDIS_PATH` in wp-config.php. it worked fine once I also defined `WP_REDIS_HOST` (though only defining HOST and not PATH failed as well, had to have both).

version 2.2.2

```
define( 'WP_REDIS_SCHEME', 'unix' );
define( 'WP_REDIS_HOST', '/home/whatever/redis/redis.sock' );
define( 'WP_REDIS_PATH', '/home/whatever/redis/redis.sock' );
```

**Comment by uhlhosting** [comment]
@tillkruss I can confirm that in my case to work with socks, it needs both HOST and PATH defined.

**Comment by tillkruss** [comment]
Yuck, we'll fix that.

**Comment by tillkruss** [comment]
@uhlhosting This is when using Predis, right?

**Comment by uhlhosting** [comment]
@tillkruss it seems there was a server side issue on my side, it seem to work as designed.

**Comment by tillkruss** [comment]
This only applied to Predis, not PhpRedis.
