### ISSUE TITLE
Validation conflict with perflab plugin

### ISSUE THREAD

**Issue by yogeshbeniwal** [rhubarbgroup/redis-cache#405]
https://github.com/WordPress/performance/pull/553 put a wrapper around object-cache.php and replace original. This is resulting in `A foreign object cache drop-in was found. To use Redis for object caching, please enable the drop-in.`

**Comment by tillkruss** [comment]
It may make sense for perflab to set this:

https://github.com/rhubarbgroup/redis-cache/blob/3e7152a706dd1da75769f33aa104df3de75af108/includes/class-plugin.php#L438-L451

**Comment by tillkruss** [comment]
See https://github.com/WordPress/performance/issues/612

**Comment by tillkruss** [comment]
closed via 9dd6dc6
