### ISSUE TITLE
Test every supported release of Relay extension

### ISSUE THREAD

**Issue by szepeviktor** [rhubarbgroup/redis-cache#409]
@tillkruss How can one determine what versions are supported?

https://github.com/cachewerk/relay/releases

**Comment by tillkruss** [comment]
We support 7.4 - 8.2

**Comment by szepeviktor** [comment]
I mean Relay version.

**Comment by tillkruss** [comment]
Elaborate?

**Comment by szepeviktor** [comment]
Currently we run a CI workflow with only a single Relay extension version.
We should run CI with **all supported** Relay versions making sure that our supported versions all work properly.

**Comment by tillkruss** [comment]
We have >5000 tests for Relay, I'd say just test two version, something relatively recent and one old one.

**Comment by szepeviktor** [comment]
> We have >5000 tests for Relay

Excuse me but union type was not spotted with those tests.

What Relay version is **not** supported?

**Comment by tillkruss** [comment]
> > We have >5000 tests for Relay
> Excuse me but union type was not spotted with those tests.

I'm referring to Relay, not the stubs. `.stub.php` files aren't actually valid PHP.


> What Relay version is **not** supported?

I don't understand the question.

**Comment by szepeviktor** [comment]
> I'm referring to Relay, not the stubs. `.stub.php` files aren't actually valid PHP.

AFAIK the union type is in the extension's code. In this repo's CI there are no stubs.

> > What Relay version is **not** supported?
> 
> I don't understand the question.

I'm trying to find out what Redis versions you support.
Could you give me a list or a way to find out?
