### ISSUE TITLE
Redis cluster with password and username

### ISSUE THREAD

**Issue by Rahe** [rhubarbgroup/redis-cache#412]
Hello,

I'm using the WP_REDIS_CLUSTER and predis client.
I'm on a case where the redis cluster have a password **and** a username.
But I do not see on the plugin a way to set the username.

I've tried to add a `username=xxx` to the host with `tls://...` but no use.
And in the code i've seen 
```
                if ( isset( $parameters['password'] ) ) {
                    $options['parameters']['password'] = WP_REDIS_PASSWORD;
                }
```
But no username.

Nicolas,

**Comment by tillkruss** [comment]
Which client are you using?

**Comment by Rahe** [comment]
Hello,

as said : predis client :)

Nicolas,

**Comment by tillkruss** [comment]
Yeah, looks like you need to open a PR to populate `username` when it's set:

https://github.com/rhubarbgroup/redis-cache/blob/2302ed3542bf39d704d1e8aed382ef826d80ab63/includes/object-cache.php#L875-L877

**Comment by tillkruss** [comment]
When using PhpRedis, you can use cluster usernames:

```php
define('WP_REDIS_PASSWORD', ['username', 'secret-password']);
```
