### ISSUE TITLE
Amp Site Scan Failed

### ISSUE THREAD

**Issue by khabarsatta** [rhubarbgroup/redis-cache#413]
Amp site scan failed with redis plugin.. i contacted with amp plugin support they say remove footnote in WP_REDIS_CONFIG chck link[Check this link](https://wordpress.org/support/topic/redis-cache-pro-causing-conflicts-with-amp-sitescan/)  

define('WP_REDIS_CONFIG', [
....
'analytics' => [
	'footnote' => false
],
]);

**Comment by tillkruss** [comment]
Aha. We can dig into this.

Which AMP plugin are you using?

**Comment by khabarsatta** [comment]
I am using official amp plugin [Official Amp Plugin Link](https://wordpress.org/plugins/amp/)

**Comment by tillkruss** [comment]
We'll fix this in the next release. In the meantime the `footnote` works 👍

**Comment by tillkruss** [comment]
Fixed in the latest release.
