### ISSUE TITLE
WordPress doesn't clean up after itself

### ISSUE THREAD

**Issue by kamilgrzegorczyk** [rhubarbgroup/redis-cache#417]
Hello,

Since 6.1 we have posts query caching available to us. 

As the feature is based on `last_changed` value of the `posts` cache group which is suffixed to the `cache_keys` therefore any action which bumps up `last_changed` invalidates all the past keys.

Unfortunately as that action happens quite often (it is enough to open empty `add post` screen) therefore tons of the keys are getting invalid and piling up in the Redis memory. On a heavy traffic sites it can be hundred thousands of keys per day which just add up over time what can lead to OOM
By default we (and probably most of the devs in here) operate on the default infinite TTL as usually it was working flawlessly and no memory leaks were happening for years until now ;)

Now I am aware that there are various solutions to that problem **but all of them are flawed IMO** and fix the symptoms and not the cause **and are counter productive in the context of proper caching**:
- we can have a filter on `cache set` to set lower TTL for the query caching (this is what I am doing temporarily) - but I am not a fan of any arbitrary magic number
- we can leverage keys eviction policy - but why should we operate constantly on almost full storage and why should we evict the keys which are valid - that's counterproductive
- we can also turn off query caching - but then again - that is quite nice feature and we should be able to leverage it.

All that "butts" ( :D ) lead me to the fact that we are trying to go around something which is flawed by design in Core WP.
That is why I have opened a Trac ticket in here:
https://core.trac.wordpress.org/ticket/57625

**As the discussion started to pick up I would love your opinion in there @tillkruss - as you have the most experience and you can tell what is possible and what not. Especially that at the moment we have the attention of the WordPress Core team.**

I think the best solution (if nothing changes in the Core) would be to have a Cron job which scans `last_updated` and runs the selective flush on some time based interval - I can write such solution for myself but that problem exists for every one of us therefore I am asking if there is a possibility to have more generic solution in the plugin?

**Comment by tillkruss** [comment]
@kamilgrzegorczyk Thanks for bringing this up.

> As the feature is based on `last_changed` value of the `posts` cache group which is suffixed to the `cache_keys` therefore any action which bumps up `last_changed` invalidates all the past keys.
> Unfortunately as that action happens quite often (it is enough to open empty `add post` screen) therefore tons of the keys are getting invalid and piling up in the Redis memory.

Would you mind illustrating this with short `MONITOR` logs?

**Comment by kamilgrzegorczyk** [comment]
Hey @tillkruss  - yes basically that is exactly the case as on your screen - when Core generates the cache key for wp_query it uses md5 to build the hash for the args and then it suffixes the `last_changed` microtime from the `posts` group. I believe you know that better than me anyway (especially when seeing your answer in Trac)  ;)

Unfortunately it never takes care of flushing the old keys and as the group is persistent these just pile up over time.
And as that `last_changed` gets bumped up very, very often therefore the amount of invalid keys is quite high.

I can definitely provide you with any logs just let me know how should I produce them (you want to just get some keys examples or?)  but the case is IMO quite obvious for you.

**Comment by tillkruss** [comment]
This makes perfect sense. Let's see where [57625](https://core.trac.wordpress.org/ticket/57625) goes and if we can get it into 6.2.

**Comment by kamilgrzegorczyk** [comment]
We will see, somehow the discussion is getting awkward at times ;)

**Comment by tillkruss** [comment]
The new cache groups were merged into core (6.3): https://github.com/WordPress/wordpress-develop/commit/82cd43419448c343cc3df41f6e37c6185e480038

**Comment by tillkruss** [comment]
Now that `wp_cache_set_last_changed()` has been merged in WordPress 6.3 and we have all the new [`*-queries` cache groups](https://make.wordpress.org/core/2023/07/17/improvements-to-the-cache-api-in-wordpress-6-3/) this can actually be solved. 

We're going to implement this in Object Cache Pro, because it's a total bitch. Feel free to send a PR with support to Redis Object Cache.

**Comment by tillkruss** [comment]
Potential solution in core: https://core.trac.wordpress.org/ticket/59592

**Comment by kamilgrzegorczyk** [comment]
That's quite promising ;)
