### ISSUE TITLE
Dashboard widget should not be displayed for all user roles

### ISSUE THREAD

**Issue by LittleBigThing** [rhubarbgroup/redis-cache#426]
I have noticed that the WordPress dashboard widget of the plugin appears for all user roles.
IMHO, I think that the widget is **only useful for administrators**. Definitely not for users roles with much lower capabilities (such as subscribers and contributors). I would opt to only display it for site admins.

Also, notie that the **link to the settings page** (in the right top corner of the widget) is always shown and it is only accessible for admins (other users get the default WP notice that they can't access this page after clicking on it).

Would you also consider how this change effects _WP multisite_? For multisite, it might be interesting to have the widget only for super admins (or with an option for super admins to disable it for single site admins.

I noticed that clients appear to be confused thinking it is some kind of website visitors analytics data. :-)

Thanks very much, also for the plugin, a great one!

**Comment by tillkruss** [comment]
Good point, Object Cache Pro does hide it.
