### ISSUE TITLE
Flush cache for particular post

### ISSUE THREAD

**Issue by pawmanaloto** [rhubarbgroup/redis-cache#430]
How do I flush the cache for particular post on save? I know I can use the save_post hook but is there a way to also remove the post meta and relation cache that comes with the post?

**Comment by A5hleyRich** [comment]
WordPress handles cache flushing internally. You do not need to manually flush the object cache unless you're saving/updating posts in a non-standard way, for example, if you're not using the WordPress built-in functions https://developer.wordpress.org/reference/functions/wp_update_post/

**Comment by tillkruss** [comment]
@pawmanaloto There is also `clean_post_cache()`

https://developer.wordpress.org/reference/functions/clean_post_cache/
