### ISSUE TITLE
Add Support for Redis renamed commands

### ISSUE THREAD

**Issue by cinghie** [rhubarbgroup/redis-cache#431]
Hi,

to implement redis security it is often recommended rename commands in the configuration file

/etc/redis/redis.conf

However, this feature is not compatible with the plugin. 
It would be important to be able to set the new commands at least for

rename-command CONFIG CONFIG_NEW
rename-command DEBUG DEBUG_NEW
rename-command FLUSHDB FLUSHDB_NEW
rename-command FLUSHALL FLUSHALL_NEW
rename-command SHUTDOWN SHUTDOWN_NEW

Regards

**Comment by tillkruss** [comment]
No, this will never be supported. It's a bad practice.
