### ISSUE TITLE
Addition of custom options hook/filters

### ISSUE THREAD

**Issue by damsean102** [rhubarbgroup/redis-cache#433]
Hi,

I was just wondering if there was any plans/thought about introducing a hook/filter to allow other developers the ability to define the settings that can be used [here](https://github.com/rhubarbgroup/redis-cache/blob/main/includes/object-cache.php#L635)?

The reason I ask is that a need has arose for us to connect to REDIS via TLS and where our REDIS server is hosted (Heroku) requires us to alter some of the [SSL parameters](https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-with-predis) (verify_peer & verify_peer_name) which currently isn't possible using the plugin.
I realise this is a feature of [Object Cache Pro](https://objectcache.pro/docs/configuration-options/#tls-options), but I was wondering if it is likely to make it's way to the free version or not?

Thanks in advance,
Sam

**Comment by tillkruss** [comment]
Hey Sam, you can't use filters, because `object-cache.php` is loaded way before you can register them. We can add a new `WP_REDIS_?` constant tho to disable TLS verification.

You'd just need to ensure it works for PhpRedis as well as Predis. They do that differently.

**Comment by damsean102** [comment]
Hi Till,

Thanks for the speedy reply! Yeah good point about the hooks, a constant could work well though. Something like WP_REDIS_TLS or something more generic (WP_REDIS_CONFIG) where we can pass client appropriate parameters into the Redis or Predis classes would be great.

I can spin up a new REDIS instance and test both those is that helps?

Thanks

**Comment by tillkruss** [comment]
Yup sounds good 👍

**Comment by david-donachie** [comment]
And here I am just sending you an email about the exact same issue! We are stuck in the same issue, where we can't connect to Heroku's self-signed Redis because we can't pass those SSL parameters. Since Heroku will force the upgrade by the 24th of April, this is pretty urgent for us.

Anything we can do to help?

**Comment by tillkruss** [comment]
You might be able to send the TLS parameters when using Predis.

**Comment by david-donachie** [comment]
> You might be able to send the TLS parameters when using Predis.

Not sure I understand? Do you mean that the SSL parameters might be read by Predis from somewhere external to the Wordpress configuration?

**Comment by tillkruss** [comment]
As mentioned by email, Object Cache Pro fully supports TLS and configuration of it.

If you want to open a PR with TLS and it's options for Predis+PhpRedis we gladly merge it.

**Comment by david-donachie** [comment]
> If you want to open a PR with TLS and it's options for Predis+PhpRedis we gladly merge it.

PR created. I went with the simplest possible setting of SSL parameters to work around the issue.
