### ISSUE TITLE
No user authentication

### ISSUE THREAD

**Issue by NizarBlond** [rhubarbgroup/redis-cache#434]
I am trying to connect via USER + PASS, but the plugin doesn't support this as you claim in the documentation page.

`WP_REDIS_PASSWORDL The password of the Redis server, supports ACLs array: ['username', 'password']
`

I use Predis. I looked at the code and you don't consider the username at all and 

`
                    $options['parameters']['password'] = WP_REDIS_PASSWORD;
`

Any idea? For security reason, we want to have a user per website.

**Comment by tillkruss** [comment]
It works with PhpRedis for sure. Predis might need a PR to make it work.

**Comment by tillkruss** [comment]
Feel free to open a PR to make it work with Predis.
