### ISSUE TITLE
Filesystem issue but author can't give support

### ISSUE THREAD

**Issue by CommittotheIndian** [rhubarbgroup/redis-cache#436]
I opened an issue in https://github.com/rhubarbgroup/redis-cache/issues/435#issue-1629310888 but the author seems to think giving half ass answers is helpful to anyone.

This question has been asked multiple times across multiple venues but @tillkruss  refuses to provide  any type of assistance in troubleshooting the issue.

So if anyone else could assist with this issue, it would be appreciated but I presume this issue will get prematurely closed and locked as well.

**Comment by tillkruss** [comment]
I'm not having this kind of attitude. Blocking you from the organization.
