### ISSUE TITLE
cache load old data 

### ISSUE THREAD

**Issue by amirakbari** [rhubarbgroup/redis-cache#443]
Hello there
Some times redis load old data cache in wordpress+woocommerce in price of product or product quantity.
Even when we flush the cache, the problem persists.
after open edit product page and update page one by one, cache data updated and show correct data of product(price/quantity)
php7.4
wordpress 6.1
httpd+nginx

**Comment by tillkruss** [comment]
Check the FAQ.

That happens when your theme or plugins don't work with persistent object caches. It's best to contact the author to fix it, or ignore the cache groups.
