### ISSUE TITLE
Error when i try to install object-cache-pro with composer ( for BedRock )

### ISSUE THREAD

**Issue by AlexJuzto** [rhubarbgroup/redis-cache#445]
Hi!

This happens to someone else, I'm trying to install object-cache-pro in my local (I've already authenticated myself and put the repository in composer.json ) but when installing with the command composer require rhubarbgroup/object-cache- pro

I get this error: Package rhubarbgroup/object-cache-pro has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - rhubarbgroup/object-cache-pro v1.18.1 requires ext-redis ^3.1.1  ^4.0  ^5.0 but it is not present.
![Screen Shot 2023-03-31 at 10 05 12 AM](https://user-images.githubusercontent.com/123690951/229160669-4a4f2efa-dc42-4f9f-9b48-89b05eb7db56.png)

This happens in my mac with valet

**Comment by tillkruss** [comment]
You need PhpRedis: https://github.com/phpredis/phpredis
