### ISSUE TITLE
redis fatal errors after upgrade to version 2.3.0

### ISSUE THREAD

**Issue by adlershai** [rhubarbgroup/redis-cache#453]
Since we upgraded last week we get fatal errors in our log files
We noticed it while trying to troubleshoot why we don't receive WooCommerce purchase email notifications
Once we stopped the Redis cache all works as expeted
[prettyballerinas_co_il.php.error.log](https://github.com/rhubarbgroup/redis-cache/files/11242423/prettyballerinas_co_il.php.error.log)

**Comment by tillkruss** [comment]
Check out the FAQ: https://github.com/rhubarbgroup/redis-cache/blob/develop/FAQ.md

`read error on connection` mean your Redis server is not available.

Please post your diagnostics from the plugin.

**Comment by adlershai** [comment]
attached + a screenshot of the error in WooCommerce GUI
[redis.txt](https://github.com/rhubarbgroup/redis-cache/files/11243827/redis.txt)
![Screenshot 2023-04-16 235555](https://user-images.githubusercontent.com/24780366/232342233-6790a4d0-1b12-48e6-b4f0-86c1bf0baf02.jpg)

**Comment by tillkruss** [comment]
It says "Connected" now. That good 👍
