### ISSUE TITLE
Prevent first time critical errors

### ISSUE THREAD

**Issue by A5hleyRich** [rhubarbgroup/redis-cache#458]
As discussed in Slack, we allow users to enable Redis Object Cache without determining if Redis is reachable. This can lead to 500 errors after the drop-in is placed in situ.

We should not allow Redis Object Cache to be enabled via the UI if Redis cannot be reached and surface any errors. Now might also be a good time to improve the Overview tab.

<img width="933" alt="CleanShot 2023-04-24 at 13 24 56@2x" src="https://user-images.githubusercontent.com/1422996/233999156-3ad1c6f5-00fd-4785-b1f5-e72b9ed911bf.png">

- [x] Overview title removed because it's redundant
- [x] Status severity reduced to a warning because not being enabled isn't an error. Also made the copy more friendly for those not familiar with drop-ins.
- [x] Drop-in row removed because it's redundant if the plugin isn't enabled
- [x] New chunky icons

<img width="933" alt="CleanShot 2023-04-24 at 13 23 39@2x" src="https://user-images.githubusercontent.com/1422996/233999200-37be5683-9b93-46a2-8637-b0129e07679a.png">

- [x] New notice indicating that Redis cannot be enabled
- [x] Enable button is disabled if the Filesystem or Redis checks fail

<img width="933" alt="CleanShot 2023-04-24 at 13 30 25@2x" src="https://user-images.githubusercontent.com/1422996/234000880-46f679b9-e8c5-485c-b901-19e3491a8f44.png">

<img width="933" alt="CleanShot 2023-04-24 at 13 32 15@2x" src="https://user-images.githubusercontent.com/1422996/234001355-8f799876-92c6-475e-9c57-72dbb778d232.png">

- [x] Status row and Drop-in rows merged. More appropriate copy for the success state.

**Comment by A5hleyRich** [comment]
We might want to do the same for the CLI command:

<img width="671" alt="CleanShot 2023-04-24 at 14 07 58@2x" src="https://user-images.githubusercontent.com/1422996/234005641-6ac93587-2f9f-432e-a7b2-45dd6d070868.png">

**Comment by tillkruss** [comment]
This is fantastic. Two tiny notes:

I think "Not enabled" instead of "Redis Object Cache not enabled" reads nicer.

If Redis is not reachable, **and** the user did **not** configure `WP_REDIS_*` constants then we should say, you need to RTFM with a link.

**Comment by A5hleyRich** [comment]
Implementation of this isn't as easy as I thought because `WP_Object_Cache` is defined in `object-cache.php`. For us to check the connection from the plugin, we need to be able to connect to Redis without `object-cache.php` being in place. 

Here's what I'm thinking:

1. Bring `WP_Object_Cache` into the plugin namespace
2. Include `WP_Object_Cache` from `object-cache.php`

Do you see any issue with this @tillkruss?

**Comment by A5hleyRich** [comment]
> Can we use the `includes/object-cache.php` somehow?

This gets hairy pretty quickly because of the global function declarations and `WP_Object_Cache` as they're already defined in `wp-includes/cache.php` if an external object cache isn't in use. Just to be able to load `includes/object-cache.php`, we need to make sure we're not redeclaring anything, which in turn means we don't have access to the connection methods without extracting them from `WP_Object_Cache`. See:

https://github.com/rhubarbgroup/redis-cache/commit/ec8a4429770d6decfdee56e5ee84c6166ec0b65f

Any other thoughts? I'm leaning toward the safest approach, which will be to duplicate the connection logic in the plugin.

**Comment by tillkruss** [comment]
Yeah, ec8a442 is way too messy. Why don't we just use Predis and try to connect in a standalone function?
