### ISSUE TITLE
Flushing Redis cache should not redirect to Redis settings

### ISSUE THREAD

**Issue by MatzeKitt** [rhubarbgroup/redis-cache#459]
Currently, if you flush the cache in the admin bar from whatever page, you will be redirected to the settings page of the Redis cache. At least on multisites. I think this is a bad user experience, since there is no indication that you will be redirected to said page nor can it be argued as intended, since there is a dedicated settings link below.

**Comment by tillkruss** [comment]
@MatzeKitt: It is not great. If we'd essentially reload the current page, then how/where would you display the "cache was flushed" message?

**Comment by MatzeKitt** [comment]
Maybe replace the link with an Ajax functionality and then use JavaScript to properly display this information.

**Comment by tillkruss** [comment]
AJAX and then the user reloads manually, or AJAX + auto reload and display a message?

**Comment by MatzeKitt** [comment]
If you clear the cache via Ajax, there is no need to reload the page. Just flush, reset the statistics in the admin bar and display a message.

**Comment by MatzeKitt** [comment]
Unfortunately, I’m currently unable to do that. And it’s also pretty low on my priority list. It was just something I quickly noticed that can be improved. 🙂

**Comment by tillkruss** [comment]
We'll keep this open 👍

**Comment by tillkruss** [comment]
See #466.
