### ISSUE TITLE
Tweak filesystem warning

### ISSUE THREAD

**Issue by tillkruss** [rhubarbgroup/redis-cache#513]
See #512.

![312829076-b2cfdcc4-871c-42c4-beb1-c9e1844be0ed](https://github.com/rhubarbgroup/redis-cache/assets/665029/1839e1c7-475b-4f85-8eea-7adb07f7a4ce)

I think we need some changes here.

1. When `DISALLOW_FILE_MODS` is set, then show a grayed out message that says "Disabled"
2. When the existing `objectcache_check_filesystem` is set, hide the row entirely

**Comment by yatsukhnenko** [comment]
@tillkruss Something like this?

![image](https://github.com/rhubarbgroup/redis-cache/assets/1374472/3085acaa-0f9f-4f53-bf6b-4883e6f613db)

**Comment by tillkruss** [comment]
That looks good!

**Comment by tillkruss** [comment]
That looks good!
