### ISSUE TITLE
Config question (agregate) for existing working redis cluster

### ISSUE THREAD

**Issue by ramonfincken** [rhubarbgroup/redis-cache#525]
We have a working redis cluster on 3 machines.

However we run the site on 2 other nodes and want to expand the cluster to them as well. So 5 redis instances as 1 cluster.
We want to connect to the 2 newest redis instances to reduce network necessity. 

We are using phpredis

I have read https://github.com/rhubarbgroup/redis-cache/issues/88 https://github.com/rhubarbgroup/redis-cache/issues/311 and https://github.com/rhubarbgroup/redis-cache/issues/26#issuecomment-208081505 plus checked your commit from 2016-04-11 (Added aggregate connections for Predis).

I am a bit confused, how can we "promote" 2 of the 5 instances to be the preferred ones for reading? We want to let redis cluster still be working as intended, to in the end all 5 could handle writes and syncs.

**Comment by tillkruss** [comment]
All your WordPress instances must point at the same Redis Cluster `master` node(s). You can get that info by running `redis-cli info | grep ^role`

```php
define( 'WP_REDIS_CLIENT', 'phpredis' );

define( 'WP_REDIS_CLUSTER', [
    'tcp://0.0.0.1:6379',
    'tcp://0.0.0.2:6380',
    'tcp://0.0.0.3:6381',
] );
```
