### ISSUE TITLE
Uncaught Error: Call to a member function get on `null`

### ISSUE THREAD

**Issue by fadimoubassaleh** [rhubarbgroup/redis-cache#526]
## Description

I'm facing a problem with tuning the plugin once enable the cache it shows and error I will send a screenshot for it
![333318043-42957297-535f-46eb-80ea-29ce7c0efc7f](https://github.com/rhubarbgroup/redis-cache/assets/33605551/a9ba48d0-75a9-498d-828f-e7e66b8a1019)
## Steps to Reproduce

1. click on enable
2. it break the website and show error in file object-cache.php
3.
4.

## Environment

* Plugin version: Version 2.5.2 
* PHP version:8.1.28 
* WordPress version: 6.5.3

**Comment by tillkruss** [comment]
This was fixed in #533.
