### ISSUE TITLE
The CPU of redis suddenly increased, causing my site to crash

### ISSUE THREAD

**Issue by cloud-arrow** [rhubarbgroup/redis-cache#536]
## Description

1. Redis monitoring found a large number of flushdb and DUMP wp-object-db:analytics:measurements

<img width="1122" alt="截屏2024-06-21 15 03 34" src="https://github.com/rhubarbgroup/redis-cache/assets/52516729/9f68d509-9200-4a83-91b2-3c96c4e88726">

<img width="1151" alt="rftdbw9Zwm" src="https://github.com/rhubarbgroup/redis-cache/assets/52516729/07b34540-81d6-44d2-852c-0183fd7445d4">

## Steps to Reproduce

1.
3.
4.
5.

## Environment

* Plugin version:
* PHP version:
* WordPress version:

**Comment by tillkruss** [comment]
You can disable the persisting of cache analytics:

define('WP_REDIS_CONFIG', [
    'analytics' => [
        'enabled' => true,
        'persist' => false, // turn `DUMP` off
    ],
]);
