### ISSUE TITLE
Cache Issues with Identical WordPress Instances Using Redis Behind AWS ALB

### ISSUE THREAD

**Issue by allweek** [rhubarbgroup/redis-cache#545]
I reported the bug here https://github.com/rhubarbgroup/redis-cache/issues/542#issuecomment-2275424424, but the issue was closed. 
Could you answer my last question:

"We have two WordPress instances, and requests to them are routed via an AWS ALB. These servers are identical twins, and they use the same Redis server.
Settings are the same in Redis Cache Plugin, including the WP_REDIS_PREFIX and WP_CACHE_KEY_SALT values (different values also don't work correctly)."

**Comment by tillkruss** [comment]
Both WordPress application servers, must use the same central Redis Server and must use the same identical `WP_REDIS_*` configuration.
