### ISSUE TITLE
Cache miss and cache hit for boolean `false` value are indistinguishable

### ISSUE THREAD

**Issue by nickchomey** [rhubarbgroup/redis-cache#552]
The [get()](https://github.com/rhubarbgroup/redis-cache/blob/f76253c6d19f98f5f77b299545c788f2da19a852/includes/object-cache.php#L1997C9-L2006C10) function doesn't distinguish between when there's a cache miss and a cached boolean value of `false` is returned.

## Description

Perhaps I am missing something fundamental, but how are we supposed to store values of boolean `false` in the object cache? If I do this, it sets appropriately. And when the key is retrieved, it is treated as a cache hit for the stats because has been serialized. All good.

Except if there's cache miss, it returns `false` (or perhaps `null` in some cases) and then sets both to `false`, which is thereby indistinguishable from real false values unless we were to somehow check to see if it was a cache miss.

This would result in continually re-setting the key to false if we're using this to avoid a complicated calculation or db query.

We can, of course, set other values - `1/0`, `"true"/"false"` and then convert to booleans or use as-is, but it really would be good to be able to set genuine boolean values and then receive a different value for a cache miss. 

## Expected Behavior

I would expect some other value to be returned for a cache miss - be it `null` or something else. 

## Actual Behavior

Cache miss and cache hit for a boolean value of `false` both return `false`. 

## Possible Fix

Return `null` for a cache miss? Of course, this might have a lot of knock-on effects for existing code that has worked around this.. 

## Steps to Reproduce

1. Try to `get` a key that hasn't yet been set. Returns `false`
2. Set the key to boolean `false`. 
3. `get` the key again. Returns `false`. 

## Additional context

Adds a lot of complication to my php code, because I have to add mechanisms to convert between boolean values and strings/ints that can be stored in the object cache, then convert back to boolean.

**Comment by tillkruss** [comment]
That's the WordPress object cache API standard. If you need to store Boolean values in the cache use integers or a string representation. 

In an ideal world the cache would return `null`, but WordPress is ancient.
