### ISSUE TITLE
Error screen showing to all users

### ISSUE THREAD

**Issue by qcybb** [rhubarbgroup/redis-cache#554]
I really appreciate all your hard work on this plugin, but I'm unable to use it for the following issue.

## Description
When the plugin is activated and Redis server is not currently running (server restart, restarting the service, server error shutdown), anyone visiting the website will see the "Error establishing a Redis connection" screen. 

## Expected Behavior
The plugin should only show this error screen to logged in admins, and continue to silently serve the website without using Redis.

## Actual Behavior
The website shows an error screen to everyone, essentially shutting down the website.

One of my blogs that I want to use it on receives a lot of traffic, and I can't chance that if the Redis server goes down, no one can access the blog until I'm even aware there's an issue.

**Comment by tillkruss** [comment]
If you disable `WP_DEBUG` then the screen will be more generic and reveal less technical information.

**Comment by qcybb** [comment]
It's not so much the error message, it's the fact that the website is completely offline to everyone until Redis is back online.
