### ISSUE TITLE
CROSSSLOT Keys in request don’t hash to the same slot with Amazon Linux 2 and AWS ElastiCache Redis OSS

### ISSUE THREAD

**Issue by laurent-le-graverend** [rhubarbgroup/redis-cache#558]
## Description

We are trying to configure this plugin with a new Redis instance.

We are experiencing the following error when using the Redis Object Cache plugin with AWS ElastiCache Redis OSS on Amazon Linux 2:

```
CROSSSLOT Keys in request don't hash to the same slot
```

<img width="400" alt="image" src="https://github.com/user-attachments/assets/50a7a874-fe17-4a09-aac8-63b8924f3f82">

## Additional Context

We are using the following stack:
	•	OS: Amazon Linux 2
	•	Redis: AWS ElastiCache Redis OSS
	•	Environment: Predis PHP client with TLS enabled
	•	PHP 8.1, WordPress 6.7.1
	•	Error occurrence: During taxonomy-related queries (get_terms, _prime_term_caches) and post-related queries (WP_Query).

## Short Stack Trace example:

```
Predis\Response\ServerException: CROSSSLOT Keys in request don't hash to the same slot in /var/www/wordpress/nme/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Client.php:384
Stack trace:
#0 /var/www/wordpress/nme/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Client.php(353): Predis\Client->onErrorResponse(Object(Predis\Command\Redis\MGET), Object(Predis\Response\Error))
#1 /var/www/wordpress/nme/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Client.php(304): Predis\Client->executeCommand(Object(Predis\Command\Redis\MGET))
#2 /var/www/wordpress/nme/wp-content/object-cache.php(2127): Predis\Client->__call('mget', Array)
#3 /var/www/wordpress/nme/wp-content/object-cache.php(208): WP_Object_Cache->get_multiple(Array, 'terms', false)
#4 /var/www/wordpress/nme/wp-includes/functions.php(7257): wp_cache_get_multiple(Array, 'terms')
#5 /var/www/wordpress/nme/wp-includes/taxonomy.php(4098): _get_non_cached_ids(Array, 'terms')
...
```

**Comment by tillkruss** [comment]
Cluster Mode enabled in Elasticache?

**Comment by laurent-le-graverend** [comment]
@tillkruss I think so.

It seems to be in cluster mode by design.

*ElastiCache Serverless*

> ElastiCache Serverless runs Redis OSS in *cluster mode* and is only compatible with clients that support TLS.

https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/WhatIs.corecomponents.html#WhatIs.HowELCworks

**Comment by tillkruss** [comment]
Cluster mode is overkill. I'd disable it. 

Regardless please post your config.

**Comment by laurent-le-graverend** [comment]
After checking with the AWS team:

> AWS ElastiCache Redis OSS Serverless is running in cluster mode enabled. ElastiCache Serverless operates Redis engines in cluster mode enabled only. Clients must support cluster mode enabled to connect to ElastiCache Serverless.

So that's not an option to disable it.

Is there a way to enable the cluster mode from this plugin, with one endpoint only and using *Predis*?

**Comment by tillkruss** [comment]
Yes 👍

**Comment by laurent-le-graverend** [comment]
@tillkruss 

I tried several config, but couldn't find one to make it work in cluster mode using Predis.

Config:

```php
define( 'WP_REDIS_SCHEME', 'tls' );
define( 'WP_REDIS_CLIENT', 'predis' );
define( 'WP_REDIS_CLUSTER', [
    'tcp://obfuscated-name.serverless.use1.cache.amazonaws.com:6379?alias=node-01',
]);
```

Conf:

```
Status: Not enabled
Client: predis
Drop-in: Not installed
Disabled: No
PhpRedis: Not loaded
Relay: Not loaded
Predis: 2.1.2
Credis: Not loaded
PHP Version: 8.2.23
Plugin Version: 2.5.4
Redis Version: Unknown
Multisite: No
Metrics: Disabled
Metrics recorded: 0
Filesystem: Writable
WP_REDIS_CLIENT: "predis"
WP_REDIS_SCHEME: "tls"
WP_REDIS_SERVERS: [
    "tls://obfuscated-name.serverless.use1.cache.amazonaws.com:6379?role=master"
]
WP_CACHE_KEY_SALT: "obfuscated-salt"
```

Can you please take a look and see if there's something we are missing?

**Comment by tillkruss** [comment]
Your constants and diagnostics do not match. See `WP_REDIS_CLUSTER` vs `WP_REDIS_SERVERS`.

**Comment by tillkruss** [comment]
@laurent-le-graverend Great, want to post the patch? We might be able to fix that up.
